### ISSUE TITLE
Add max deposit functionality to fund market widget

### ISSUE THREAD

**Issue by KadenZipfel** [protofire/omen-exchange#1001]
Should be an option to allow users to set the funding to their wallet balance.

**Comment by pimato** [comment]
<img width="787" alt="Screenshot 2020-07-31 at 15 07 15" src="https://user-images.githubusercontent.com/5337809/89037832-879f8400-d33f-11ea-9636-e7ce0cf0d0fc.png">

**Figma:**
[Design Specification](https://www.figma.com/file/R056tSYMjvfwaFidEBItYy/Widgets-V2?node-id=57%3A605)
