### ISSUE TITLE
Show alert message if user sets a negative fee

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#1015]
Currently, if the user wants to set a negative fee he/she can do that. We should restrict the user by showing him a warning message:
<img width="620" alt="Screenshot 2020-07-29 at 12 27 04" src="https://user-images.githubusercontent.com/5337809/88789261-d2ca6300-d196-11ea-87f3-f09ea8bdb42c.png">

**Comment by KadenZipfel** [comment]
At any time if the custom fee is invalid, do we want to display the fee as 2% in green as you have above? E.g. both if the custom fee is negative or >5

**Comment by pimato** [comment]
> At any time if the custom fee is invalid, do we want to display the fee as 2% in green as you have above? E.g. both if the custom fee is negative or >5

The best way forward would be actually to remove the "Earn Trading Fee 2%" if the user wants to set its own custom trading fee as it is redundant information.

[Playground
](https://www.figma.com/proto/GNoehJ64fqfptghsjYqvTJ/Playground-V2?node-id=3452%3A177&viewport=832%2C601%2C0.7815516591072083&scaling=min-zoom)
[Design specification](https://alchemy.daostack.io/dao/0x519b70055af55a007110b4ff99b0ea33071c720a/schemes)

**Comment by pimato** [comment]
this will be eliminated with the dropdown picker!
