### ISSUE TITLE
Issue with decimal places and custom fee

### ISSUE THREAD

**Issue by KadenZipfel** [protofire/omen-exchange#1020]
Generally when setting a custom fee, users are capped at using max. 2 decimal places. It's possible to get past this by typing '0.000...'. This appears to be bad UX, especially considering if a user types a digit other than 0 at the end of that string, it just reverts back to 0.

**Comment by pimato** [comment]
How would you fix it @KadenZipfel ? One alternative is to not have an inputfield at all but a dropdown which lets you pick:
0% , 0.25%, 0.5% and so on ... I think this could eliminate that issue!

**Comment by pimato** [comment]
<img width="608" alt="Screenshot 2020-07-31 at 15 22 35" src="https://user-images.githubusercontent.com/5337809/89039032-b0c11400-d341-11ea-903b-2e443f438b17.png">

**Figma:**[
Design Specification](https://www.figma.com/file/GNoehJ64fqfptghsjYqvTJ/Playground-V2?node-id=3460%3A9)

**Comment by KadenZipfel** [comment]
> How would you fix it @KadenZipfel ? One alternative is to not have an inputfield at all but a dropdown which lets you pick:
> 0% , 0.25%, 0.5% and so on ... I think this could eliminate that issue!

Agreed!
