### ISSUE TITLE
Possible error if funding amount is typed in as displayed balance

### ISSUE THREAD

**Issue by KadenZipfel** [protofire/omen-exchange#1021]
Due to rounding issues, typing in your displayed wallet balance can lead to an insufficient funds error. 

![image](https://user-images.githubusercontent.com/30579067/88837409-15873d80-d18d-11ea-9c7f-3245f5e5ea89.png)

Setting up https://github.com/protofire/omen-exchange/issues/1001 seems like it would be an effective solution.

Note: This is Rinkeby DAI shown in the image (I promise I'm not flexing)

**Comment by pimato** [comment]
I`ve added designs for the Max button: https://github.com/protofire/omen-exchange/issues/1001

**Comment by KadenZipfel** [comment]
Closing in favor of https://github.com/protofire/omen-exchange/issues/1001
