### ISSUE TITLE
Warn users if a market has very low liquidity

### ISSUE THREAD

**Issue by KadenZipfel** [protofire/omen-exchange#1022]
It's possible to supply only 0.000001 DAI in liquidity to a market. This can easily lead to losing trades if users aren't careful. To mitigate this, I think we should display a warning if there is less than a certain amount of liquidity.

**Comment by pimato** [comment]
similar to issue: https://github.com/protofire/omen-exchange/issues/968#issuecomment-667091087 we can add a passiv warning to the market details view to inform users that there is no liquidity:

<img width="786" alt="Screenshot 2020-07-31 at 14 41 25" src="https://user-images.githubusercontent.com/5337809/89035859-ef53d000-d33b-11ea-8777-599e6da49770.png">

This should be shown if stablecoins liquidity is lower then 50$

**Figma:**[
Design Specification](https://www.figma.com/file/R056tSYMjvfwaFidEBItYy/Widgets-V2?node-id=139%3A203)

**Comment by KadenZipfel** [comment]
> similar to issue: [#968 (comment)](https://github.com/protofire/omen-exchange/issues/968#issuecomment-667091087) we can add a passiv warning to the market details view to inform users that there is no liquidity:

The difficulty with this is having different collateral assets. For example, if we have 0.05 WETH liquidity it might be a reasonable amount. Should we check the exchange rates of assets and display the alert if there's less $0.05 USD liquidity?

**Comment by pimato** [comment]
yeah I think this will require a subgraph change which is defined here: https://github.com/protofire/omen-subgraph/issues/27

**Comment by pimato** [comment]
lets push this to the next milestone!

**Comment by KadenZipfel** [comment]
> yeah I think this will require a subgraph change which is defined here: [protofire/omen-subgraph#27](https://github.com/protofire/omen-subgraph/issues/27)

As nice as it would be to have this done at the subgraph level, we could always use an API to get the USD value of collateral tokens. I think it would generally be useful to have, and it would certainly be a lot easier to setup than via subgraph.

**Comment by pimato** [comment]
has been implemented:
<img width="614" alt="Bildschirmfoto 2020-10-08 um 18 03 40" src="https://user-images.githubusercontent.com/5337809/95484341-a4d07e80-0990-11eb-84ef-5f7d9135e634.png">
