### ISSUE TITLE
Back button doesn't work if you navigate to a market page directly.

### ISSUE THREAD

**Issue by auryn-macmillan** [protofire/omen-exchange#1026]
If you navigate directly to a market page, say by following [this link](https://omen.eth.link/#/0x021177806816d375be91ac15099dffa01906f0a2), clicking the back button does nothing. The back button works as expected if you navigate to a market from the "markets" view.

![Screen record from 2020-07-30 14 28 45](https://user-images.githubusercontent.com/8453294/88960096-05488e80-d271-11ea-8f38-b67207d7cd94.gif)

**Comment by KadenZipfel** [comment]
This should be fixed by https://github.com/protofire/omen-exchange/pull/1017. Can you pull master and try again?

**Comment by auryn-macmillan** [comment]
Ok cool. I just noticed in production today. Glad there's already a fix 😃
