### ISSUE TITLE
'My Markets' not displaying markets that a user has created

### ISSUE THREAD

**Issue by KadenZipfel** [protofire/omen-exchange#1027]
I assume this came about from making the change to start displaying markets that users have interacted with in the 'My Markets' view, but for some reason, it no longer returns a user's created markets.

**Comment by KadenZipfel** [comment]
Issue is due to market creation not being recorded as participation, additionally liquidity provision is also not recorded. https://github.com/protofire/omen-subgraph/issues/37

**Comment by pimato** [comment]
@KadenZipfel I believe this was fixed

**Comment by pimato** [comment]
Yup, seems to be fixed, gonna close it for now!
