### ISSUE TITLE
Allow markets to be filter in the My Market view

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#1084]
We should allow the user to filter their markets by:
- Ending Soon <--- Should be the default filter option
- Highest Pool Tokens
- Highes Shares

We should allow them to filter by category via the main Category Picker!

Additionally we should allow them to filter by:
- Currency
- Arbitrator

like this:
<img width="698" alt="Screenshot 2020-09-01 at 16 50 34" src="https://user-images.githubusercontent.com/5337809/91866916-546c4f80-ec73-11ea-9fd3-2869ab923219.png">

**Comment by KadenZipfel** [comment]
Some notes:
- With the current subgraph implementation, we can't filter by pool tokens or outcome shares. I've created an issue to add it to the subgraph: https://github.com/protofire/omen-subgraph/issues/53
- We should also be able to filter by curation source, which will also need a subgraph modification: https://github.com/protofire/omen-subgraph/issues/54

If I have the time I'll make PR's for these subgraph changes.
