### ISSUE TITLE
Consistent naming of market states 

### ISSUE THREAD

**Issue by KadenZipfel** [protofire/omen-exchange#1087]
Currently in the market state dropdown, we have: 'Open', 'Pending', 'Finalizing', and 'Ended'. With the new market overview widget https://github.com/protofire/omen-exchange/issues/817, we have: 'Open', 'Finalizing', 'Arbitration', and 'Closed'. It's really confusing if we have conflicting names for the market states. 

I propose we go with: 'Open', 'Finalizing', 'Arbitrating', and 'Closed'.

**Comment by pimato** [comment]
I like your proposal, lets do it!
