### ISSUE TITLE
Trade History dropdown sometimes crashes application

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#1112]
I found a bug which gets triggered when the user clicks on the trade history dropdown. I am trying to find a way to clear reproduce it:
<img width="1051" alt="Screenshot 2020-09-11 at 10 17 14" src="https://user-images.githubusercontent.com/5337809/92891283-1fe95800-f418-11ea-938f-745dc478f5d4.png">

**Comment by KadenZipfel** [comment]
I've been playing around with the history chart for a little while now but haven't been able to reproduce it, so if you could find steps to reproduce that would be awesome.

**Comment by pimato** [comment]
> I've been playing around with the history chart for a little while now but haven't been able to reproduce it, so if you could find steps to reproduce that would be awesome.

I tried to find a way to reproduce it but did not had success so far. Will investigate more.

**Comment by pimato** [comment]
Gonna close this for now until it actually appears again at some point!
