### ISSUE TITLE
Market lifecycle progress bar visible on button click

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#1115]
Hey everyone,

I believe the progress bar is separating the market question with the answers too much. Therefor, we will introduce a minimized version of the progressbar with a three dot inside a button. Once the button is clicked, users can observe the lifecycle progress bar fully.

**Idle:**
<img width="834" alt="market-open" src="https://user-images.githubusercontent.com/5337809/93763487-d36cfc00-fc11-11ea-8149-e44f1a3c57f3.png">

**Collapsed:**
<img width="834" alt="market-open-collpased" src="https://user-images.githubusercontent.com/5337809/93763611-0fa05c80-fc12-11ea-9160-d9373ba57da9.png">

**Figma:**
[Playground](https://www.figma.com/proto/GNoehJ64fqfptghsjYqvTJ/Playground-V2?node-id=4249%3A0&viewport=341%2C268%2C0.36003944277763367&scaling=min-zoom)
[Design Specification](https://www.figma.com/file/GNoehJ64fqfptghsjYqvTJ/Playground-V2?node-id=4249%3A0)

**Icons**
[Three-dots.zip](https://github.com/protofire/omen-exchange/files/5219852/Three-dots.zip)
[Three-dots-Active.zip](https://github.com/protofire/omen-exchange/files/5219866/Three-dots-Active.zip)

**Comment by Phinneas** [comment]
Okay, I'll take this one on.
