### ISSUE TITLE
Kleros curate verification process

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#1118]
Hey guys,

I´ve been working on adding the Kleros curate verification process into Omen. You can play around with the verification process in the [Playground](https://www.figma.com/proto/GNoehJ64fqfptghsjYqvTJ/Playground-V2?node-id=4217%3A0&viewport=281%2C126%2C0.16774962842464447&scaling=min-zoom).

## Verify Widget Tab
<img width="834" alt="verify" src="https://user-images.githubusercontent.com/5337809/93242176-aee2d100-f786-11ea-80bc-00d12bc6b146.png">

[Design specification](https://www.figma.com/file/GNoehJ64fqfptghsjYqvTJ/Playground-V2?node-id=4217%3A0)

## Request Verification
<img width="834" alt="request-verification" src="https://user-images.githubusercontent.com/5337809/93243086-fb7adc00-f787-11ea-9812-20ed55e25c44.png">

[Design specification](https://www.figma.com/file/GNoehJ64fqfptghsjYqvTJ/Playground-V2?node-id=4217%3A457)

## Verification Pending

<img width="834" alt="verification-pending" src="https://user-images.githubusercontent.com/5337809/93243482-8bb92100-f788-11ea-9687-decb40900f36.png">

[Design Specification](https://www.figma.com/file/GNoehJ64fqfptghsjYqvTJ/Playground-V2?node-id=4269%3A8)

## Challenge Submission 

<img width="834" alt="submission-challenge" src="https://user-images.githubusercontent.com/5337809/93243819-097d2c80-f789-11ea-87ec-88a1cc466e5e.png">

[Design Specification
](https://www.figma.com/file/GNoehJ64fqfptghsjYqvTJ/Playground-V2?node-id=4269%3A1800)

## Verified

<img width="834" alt="verification-successful" src="https://user-images.githubusercontent.com/5337809/93244160-91633680-f789-11ea-9937-82173c8eaa1b.png">

[Design Specification
](https://www.figma.com/file/GNoehJ64fqfptghsjYqvTJ/Playground-V2?node-id=4269%3A2082)

**Comment by mtsalenc** [comment]
Looks great. I presume the "Challenge Details" links to the submission on Omen Verified Markets on curate right?

**Comment by pimato** [comment]
> Looks great. I presume the "Challenge Details" links to the submission on Omen Verified Markets on curate right?

yes exactly. Button `Challenge` and `Remove` also just open a new tab and redirects to Kleros curate specific pages. I think one good thing to have is that we actually point it to the curate page with the modal open.

**Comment by KadenZipfel** [comment]
At some point we probably want to consider how we might implement a 'pending' state for dxdao market verification in which we check whether there is already an active proposal to verify that market. Otherwise users may spend unnecessary gas trying to verify a market already pending verification.
