### ISSUE TITLE
Import Market Redesign

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#1124]
Hey everyone,

with the new market creation redesign comes a new import market process as the current import flow was implemented without UX in mind.

## Import Market - Default

![import-idle](https://user-images.githubusercontent.com/5337809/93808390-324f6700-fc4c-11ea-8c28-2a60d505ca6a.png)

## Import Market - Active

![importing](https://user-images.githubusercontent.com/5337809/93808473-4eeb9f00-fc4c-11ea-9e6a-c49a900921ae.png)

## Import Market - Done

![imported](https://user-images.githubusercontent.com/5337809/93808530-6a56aa00-fc4c-11ea-9249-418d42a6d800.png)

**Figma:**
[Design Specification](https://www.figma.com/file/GNoehJ64fqfptghsjYqvTJ/Playground-V2?node-id=4359%3A2948)
[Playground](https://www.figma.com/proto/GNoehJ64fqfptghsjYqvTJ/Playground-V2?node-id=4359%3A2948&viewport=575%2C403%2C0.16246357560157776&scaling=min-zoom)

**Comment by liaojikunwork** [comment]
@pimato , please share one question url to test with.

**Comment by pimato** [comment]
http://reality.eth.link/app/#!/question/0x9b868b9873a7c7ba65cc88709b1c9998331e5866fee72de4cba4360cf3750e5d

**Comment by liaojikunwork** [comment]
@pimato , could you share another question url with manual outcomes?
