### ISSUE TITLE
Advanced filters can appear in My Markets state 

### ISSUE THREAD

**Issue by KadenZipfel** [protofire/omen-exchange#1136]
Currently, we have yet to setup advanced filters in the My Markets state, but if you set one of the filters and navigate to the My Markets state, they will stay open even though they shouldn't exist, and don't even function. Instead, advanced filters should not ever open in the My Markets state, and the URL should also reflect that, i.e. not contain the various filters.

Considering the My Markets filters are being setup right now, it may just be best to wait until then to resolve this, as it will change the solution to only needing to ensure one of the filters doesn't appear.

**Comment by pimato** [comment]
this issue has been resolved already by enabling all filters in the my market view!
