### ISSUE TITLE
`Trade Outcome` widget title shown in Pool Liquidity Widget

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#1140]
Seems like we keep the title `Trade Outcome` if the user is in the `Pool Liquidity` section. The widget should have the title `Pool Liquidity`!

Wrong:
<img width="606" alt="Bildschirmfoto 2020-10-05 um 12 25 30" src="https://user-images.githubusercontent.com/5337809/95069780-7724d480-0707-11eb-87f3-b48f558750f3.png">

Should:
<img width="606" alt="Bildschirmfoto 2020-10-05 um 12 39 31" src="https://user-images.githubusercontent.com/5337809/95070119-edc1d200-0707-11eb-88bc-61172aafafeb.png">

**Comment by KadenZipfel** [comment]
Closing as this is no longer relevant after: https://github.com/protofire/omen-exchange/pull/1155
