### ISSUE TITLE
General "Pool Token Balance" no longer showing for users

### ISSUE THREAD

**Issue by skyminert** [protofire/omen-exchange#1144]
Few notes regarding Omen on dxtest.eth:
1) It looks like "Pool Token Balance" is showing zero on all markets.
https://dxtest.eth.link/#/0x55f0b47c208296058472ad25462c612d035d465a/pool-liquidity
Then when you click "Withdraw" , it will show you "My Pool Tokens" balance, but make "Pool Token Balance" disappear, so you wouldn't see how much of the pool you are.

This used to exists, so need to figure out where we can add it back in.

**Comment by pimato** [comment]
fixed!
