### ISSUE TITLE
Filter not working when in "My Markets" (maybe not even supposed to be there!)

### ISSUE THREAD

**Issue by skyminert** [protofire/omen-exchange#1145]
Few notes regarding Omen on dxtest.eth:

When choosing "My Markets" and then filter by "Currency", it's not filtering by currency. Still showing all my markets.
https://dxtest.eth.link/#/24h-volume/currency/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/curation-source/All%20Sources?state=MY_MARKETS
When on "Open" markets, the filters seem to work.

**Comment by pimato** [comment]
this issue will be fixed via https://github.com/protofire/omen-exchange/pull/1116
