### ISSUE TITLE
Get rid of env file and hardcode values

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#1152]
current env file:
```
REACT_APP_VERSION=omen
REACT_APP_INFURA_PROJECT_ID="9c6788bb15234036991db4637638429f"
REACT_APP_MARKET_FEE=2.00
REACT_APP_GRAPH_MAINNET_HTTP='https://api.thegraph.com/subgraphs/name/protofire/omen'
REACT_APP_GRAPH_MAINNET_WS='wss://api.thegraph.com/subgraphs/name/protofire/omen'
REACT_APP_GRAPH_RINKEBY_HTTP='https://api.thegraph.com/subgraphs/name/protofire/omen-rinkeby'
REACT_APP_GRAPH_RINKEBY_WS='wss://api.thegraph.com/subgraphs/name/protofire/omen-rinkeby'
REACT_APP_KEY_INFURA_API_KEY=6ad6d4a4ec79442eacfa967652729d1c
REACT_APP_ETH_NETWORKS=mainnet
REACT_APP_GIT_SHA=4c1b9908c4fe48be3c60eed52f3892c503671d4d
NODE_ENV=production```

**Comment by KadenZipfel** [comment]
Why?

**Comment by pimato** [comment]
a few things come in mind:

- easier development because devs don´t need to deal with the env file
- those things never change
- expose infura id very openly on each proposal description

**Comment by liaojikunwork** [comment]
@pimato , removing the whole env file is not a good option, I think.
It's better to remove most of them and leave a few variables such as 'NODE_ENV', 'REACT_APP_MARKET_FEE' and 'REACT_APP_INFURA_PROJECT_ID'

**Comment by KadenZipfel** [comment]
> @pimato , removing the whole env file is not a good option, I think.
> It's better to remove most of them and leave a few variables such as 'NODE_ENV', 'REACT_APP_MARKET_FEE' and 'REACT_APP_INFURA_PROJECT_ID'
> 
> @KadenZipfel , what is your thought?

My primary concern with this is making the infura id even more public. I'd prefer if we could maintain the env file with the infura id at least and figure out a solution to keeping it private, but not sure how reasonable that is given our deployment flow.

**Comment by pimato** [comment]
> > @pimato , removing the whole env file is not a good option, I think.
> > It's better to remove most of them and leave a few variables such as 'NODE_ENV', 'REACT_APP_MARKET_FEE' and 'REACT_APP_INFURA_PROJECT_ID'
> > @KadenZipfel , what is your thought?
> 
> My primary concern with this is making the infura id even more public. I'd prefer if we could maintain the env file with the infura id at least and figure out a solution to keeping it private, but not sure how reasonable that is given our deployment flow.

where is the difference in keeping the env file with just the infura id or hardcode it in the project itself without the need of the env file at all. Those variable will very rarely change.

**Comment by hexyls** [comment]
The conditional token contract address was [changed in Rinkeby defaults](https://github.com/protofire/omen-exchange/pull/1206) to the original contract address.

This breaks markets currently indexed on the protofire/omen-rinkeby subgraph but not the gnosis/omen-rinkeby subgraph. In general just wondering which one of these subgraphs we should use going forward? The current PR is includes protofire/omen-rinkeby.

**Comment by auryn-macmillan** [comment]
I really dislike this idea.

The infuraID is public either way, so I don't think this makes a significant difference to it's security.

But this will significantly impact how easily others can clone and modify the app.
