### ISSUE TITLE
Update 'question is being resolved' message to be call to action

### ISSUE THREAD

**Issue by KadenZipfel** [protofire/omen-exchange#1154]
As we spoke about on the call today, often markets stay pending for a long time, presumably because the average user doesn't know how to resolve a question. Instead of what we have in the below screenshot, I think we should update it to have a focus on suggesting that the user go and resolve it. This could include some kind of explainer, or say something like: "This question needs resolving, go here to resolve it". Thoughts?

![image](https://user-images.githubusercontent.com/30579067/95259911-bf61f680-07dc-11eb-840a-f3cfe663dcdb.png)

**Comment by pimato** [comment]
replaced with: https://github.com/protofire/omen-exchange/pull/1369
