### ISSUE TITLE
tab description changes on navigation changes

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#1158]
in the market details view, if you are on swap you are seeing the market question in the tab like this:
<img width="243" alt="Bildschirmfoto 2020-10-07 um 23 54 59" src="https://user-images.githubusercontent.com/5337809/95392360-e6ade600-08f8-11eb-85a3-efa176020309.png">

this should not change if you switch through the horizontal navigation. Right now if you change from swap to pool you see that the tab resets to just:
<img width="245" alt="Bildschirmfoto 2020-10-07 um 23 55 09" src="https://user-images.githubusercontent.com/5337809/95392407-fa594c80-08f8-11eb-9962-a0e28b89d9a8.png">

**Comment by KadenZipfel** [comment]
This should be solved by implementing https://github.com/protofire/omen-exchange/issues/1161. I'll keep an eye on this.
