### ISSUE TITLE
After navigating through the horizontal navigation in the market details view, back button is not working correctly

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#1161]
The back button should always immediately go back to the market overview list and not go back in the horizontal navigation.

Steps to reproduce:
1. Go to a market details 
2. Navigate to pool
3. Navigate to history
4. Click back --> BUG: It goes back to pool but should go back to the market overview page

**Comment by KadenZipfel** [comment]
There is no perfect solution to this issue, but we do have options:

Option 1: 
- Have back button always go back to the home page when in a market view page.
- Caveat: Your filters that you had open will not be saved.

Option 2: 
- We can remove routing for each market navigation tab, e.g. swap, pool, history. Allowing us to go back to the home page as before implementing the market navigation
- Caveat: You can't produce a link to these different tabs, e.g. you can't share a link to pool liquidity on a market, instead users will always have to navigate to the tab they want to use.

It's also worth mentioning that the navigation is essentially the same as it was previous to implementing the horizontal navigation. Though, I do see why the flow feels different with this implementation.

**Comment by pimato** [comment]
I am accepting the tradeoff regarding Option 2 and I would still say it is worth having a back button which doesn`t go back inside the horizontal navigation.
