### ISSUE TITLE
Title not vertical aligned anymore

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#1190]
<img width="614" alt="Bildschirmfoto 2020-10-20 um 19 35 51" src="https://user-images.githubusercontent.com/5337809/96623345-86ad3b80-130b-11eb-98e1-5c19503eeb74.png">

**Comment by KadenZipfel** [comment]
I suspect it's from this commit: https://github.com/protofire/omen-exchange/commit/499857c43ce78aba932ae4d8e464a2d2a0984d2c
