### ISSUE TITLE
Add Transaction Overview to History Tab

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#1194]
On Omen there is currently no way to get an overview of the true on-chain activity of a market. The new History View combines a activity/transaction History with the History graph and will be shown as default when the user clicks on the history navigation item:

The Transaction Table contains columns:
- User with the Jazz icon representation and a shorted address which will be used as an hyperlink in the future
- Action of the transaction (Withdraw & Deposit Liquidity, Buy & Sell Shares)
- Shares/PT (If Withdraw & Deposit => Pool Tokens, if Buy & Sell => Shares)
- Amount in the Currency
- Date and Time of the transaction which is an hyperlink and redirects you to the etherscan page

<img width="714" alt="History-Activities" src="https://user-images.githubusercontent.com/5337809/96698730-c288e500-138d-11eb-8c4c-8e8bdd86751d.png">

The existing Graph will be moved into its own tab:

<img width="714" alt="History-Graph" src="https://user-images.githubusercontent.com/5337809/96698886-ea784880-138d-11eb-9fe1-7500c885b065.png">

**Figma:**
[Design Specification](https://www.figma.com/file/R056tSYMjvfwaFidEBItYy/Widgets-V2?node-id=1209%3A141)
[Playground](https://www.figma.com/proto/aTivxuHmp2l6Sn8nho1Ngu/Playground?node-id=135%3A404&viewport=640%2C325%2C0.18646815419197083&scaling=min-zoom)

**Comment by pimato** [comment]
Dropdown should look like this:
<img width="381" alt="Bildschirmfoto 2020-10-22 um 13 54 37" src="https://user-images.githubusercontent.com/5337809/96868315-25ea4400-146e-11eb-99af-73604dd9fc62.png">

[Checkout on Figma](https://www.figma.com/file/R056tSYMjvfwaFidEBItYy/Widgets-V2?node-id=1209%3A141)

**Comment by auryn-macmillan** [comment]
It would also be great if you could filter activity by address so that you could see your (and others') trading activity.
