### ISSUE TITLE
Mobile Version for Market Overview Widget

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#1196]
<img width="463" alt="Mobile-Overview" src="https://user-images.githubusercontent.com/5337809/96729860-e3fdc700-13b5-11eb-98ac-fdc2e969243e.png">

**Figma:**
[Design Specification](https://www.figma.com/file/R056tSYMjvfwaFidEBItYy/Widgets-V2?node-id=1209%3A141)

**Comment by liaojikunwork** [comment]
@pimato , how should I align if category is long? "Business & Finance"

**Comment by pimato** [comment]
@liaojikunwork it would move to the second line like this:
<img width="463" alt="Details" src="https://user-images.githubusercontent.com/5337809/96731008-13f99a00-13b7-11eb-91df-40b0276e2e0a.png">
