### ISSUE TITLE
New Market details bottom navigation

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#1217]
Currently:
<img width="612" alt="Bildschirmfoto 2020-10-26 um 12 47 41" src="https://user-images.githubusercontent.com/5337809/97168899-7cff5a00-1789-11eb-97ac-4466aa668fa1.png">

New Version:
<img width="714" alt="market-details" src="https://user-images.githubusercontent.com/5337809/97168961-94d6de00-1789-11eb-8d04-03f636e7c0e0.png">

**Figma**:
[Design Specification](https://www.figma.com/file/R056tSYMjvfwaFidEBItYy/Widgets-V2?node-id=1209%3A141)

**Comment by liaojikunwork** [comment]
@pimato , I can't see "Back" button on the current site.
And should I update styling of navigation buttons of "Swap" tab only?

**Comment by pimato** [comment]
> @pimato , I can't see "Back" button on the current site.
> And should I update styling of navigation buttons of "Swap" tab only?

Yes, please add the back button.

> And should I update styling of navigation buttons of "Swap" tab only?

Yes, please do!
