### ISSUE TITLE
Verification icon getting cut off in import market view

### ISSUE THREAD

**Issue by KadenZipfel** [protofire/omen-exchange#1227]
![image](https://user-images.githubusercontent.com/30579067/97232929-4f231100-179b-11eb-8d34-729eb97edd3f.png)

![image](https://user-images.githubusercontent.com/30579067/97232945-59450f80-179b-11eb-8e3c-b0b2fc219221.png)

**Comment by Mi-Lan** [comment]
@KadenZipfel when you mentioned this issue i thought you have given me this one https://github.com/protofire/omen-exchange/issues/1222 it seems it's a duplicate so i will close it...
