### ISSUE TITLE
Detect if a question from reality.eth has more then one market/currency and allow user to switch between those in the market details view

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#1232]
Hey guys,

now that the new designs are in place for the market details view we can start adding more features to it. One of those features is to actually indicate the user that for that specific questions there are more then one market/currency available. This is done by making a dropdown visible **only** if there are > 1 market which has the same question id from reality.eth.

<img width="714" alt="currency-picker" src="https://user-images.githubusercontent.com/5337809/97284869-dc20a580-1841-11eb-8b6c-575b2c16ce5d.png">

**Comment by liaojikunwork** [comment]
@pimato , could you share a question url(reality.eth) with several market/currency?

**Comment by pimato** [comment]
@liaojikunwork https://bafybeieixpg6uwbgbtq7namfui3nvbmoss7pqfx24m4cbkd3umxhdszl64.ipfs.dweb.link/app/#!/question/0xedbee1c81af7d5f55e064c39c8839661e84586e7b63b33d5871fd561b368b27d
