### ISSUE TITLE
Add new styling to select closing date/category button in configure market 

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#1234]
Currently:
<img width="558" alt="Bildschirmfoto 2020-10-27 um 11 40 39" src="https://user-images.githubusercontent.com/5337809/97290742-42f58d00-1849-11eb-8059-d930e9118ee6.png">

Should:
<img width="999" alt="Bildschirmfoto 2020-10-27 um 11 40 56" src="https://user-images.githubusercontent.com/5337809/97290762-4b4dc800-1849-11eb-9356-7528d16ea30f.png">

**Figma:**
[Design Specification](https://www.figma.com/file/R056tSYMjvfwaFidEBItYy/Widgets-V2?node-id=1209%3A141)

**Comment by liaojikunwork** [comment]
@pimato , the placeholders of buttons.
All in lowercase? ("select closing date", "select category")
