### ISSUE TITLE
Update Walletconnect to newest version

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#1243]
https://github.com/WalletConnect/walletconnect-monorepo/releases/tag/1.3.1

**Comment by Mi-Lan** [comment]
@pimato @KadenZipfel i was looking at Uniswap code and saw that they actually connect wallet connect via web-react and that seems like standard practice from what i searched....should i figure out a way to do it with libraries we are using ? Picture below
![Screenshot 2020-11-02 at 19 43 08](https://user-images.githubusercontent.com/33226956/97906258-a436c800-1d43-11eb-9506-519ede26514b.png)
Or with libraries that uniswap uses?
![Screenshot 2020-11-02 at 19 40 08](https://user-images.githubusercontent.com/33226956/97906174-823d4580-1d43-11eb-968b-7415da7c4472.png)

**Comment by hexyls** [comment]
This will be closed by https://github.com/protofire/omen-exchange/pull/1347
