### ISSUE TITLE
If user is connected to Rinkeby use https://reality.eth.link as a redirect to the reality.eth page

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#1264]
While connected on Rinkeby, Omen redirects me to 

`https://reality.eth/app/#!/question/0x91468cd301cb09c9f4e3bade0dabd30c84635bd0faeb04bf7c821d4c0bfff23e`

which cannot be resolved because reality.eth is not existing on Rinkeby. Therefor we should change the redirect **if** we are on Rinkeby to:

`https://reality.eth.link/app/#!/question/0x91468cd301cb09c9f4e3bade0dabd30c84635bd0faeb04bf7c821d4c0bfff23e`

**Comment by Mi-Lan** [comment]
> While connected on Rinkeby, Omen redirects me to
> 
> `https://reality.eth/app/#!/question/0x91468cd301cb09c9f4e3bade0dabd30c84635bd0faeb04bf7c821d4c0bfff23e`
> 
> which cannot be resolved because reality.eth is not existing on Rinkeby. Therefor we should change the redirect **if** we are on Rinkeby to:
> 
> `https://reality.eth.link/app/#!/question/0x91468cd301cb09c9f4e3bade0dabd30c84635bd0faeb04bf7c821d4c0bfff23e`

This change has to do with ipfs?

**Comment by pimato** [comment]
> > While connected on Rinkeby, Omen redirects me to
> > `https://reality.eth/app/#!/question/0x91468cd301cb09c9f4e3bade0dabd30c84635bd0faeb04bf7c821d4c0bfff23e`
> > which cannot be resolved because reality.eth is not existing on Rinkeby. Therefor we should change the redirect **if** we are on Rinkeby to:
> > `https://reality.eth.link/app/#!/question/0x91468cd301cb09c9f4e3bade0dabd30c84635bd0faeb04bf7c821d4c0bfff23e`
> 
> @pimato This change has to do with ipfs?

Has nothing to do with ipfs. You can simply test it out by connecting to rinkeby, pick one market and click on reality.eth here:
http://localhost:3000/#/0x5c2252f319a564a1f1d8c74801976c26fcf9d3e4
you will see that you will get redirected to a not existing page because the metamask checks what reality.eth resolves on rinkeby but there is no ENS system on Rinkeby. So we need to use the centralised URL realiy.eth.link to let the user still access reality.eth.
