### ISSUE TITLE
Allow Users to participate through the Finalization Process of an Market

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#1265]
Omen is a product which is using several protocols in combination. One of those protocols is reality.eth which provides Omen a simple and secure way to determine what outcome is actually the correct outcome of a market. User stake Ether to set an outcome of a market which will trigger the Finalization process with a duration of 24 hours. In those 24 hours anyone can stake on other outcomes which a 2x stake defined by the reality protocol. It is also to declare a market invalid.

### Finalize Page
<img width="1280" alt="Finalize" src="https://user-images.githubusercontent.com/5337809/97700972-f8744a80-1aac-11eb-8a33-e0c5abce667f.png">

- This Page will be shown once the market reached its closing date. No buying or selling anymore.
- This example picture visualizes that the Finalizing process was already triggered as someone already bonded 0.15 ETH on the outcome Republicans which has the winning icons on the left side of the outcome description.
- The time remaining indicator in the market overview widget has also changed into the timer which indicates when the Finalization process is done.
- The call Arbitrator button will at first just link to the reality.eth question page for example (http://reality.eth.link/app/#!/question/0x4cdfa97977c9752263a6774989aa8701569bcd5eb26721c4c8c479c085e996ba)
- If the market is in active arbitration, the Finalize Market

### Set Outcome
<img width="1280" alt="Finalizing" src="https://user-images.githubusercontent.com/5337809/97700993-00cc8580-1aad-11eb-886f-d21673752d3b.png">
- The currently highest staked outcome is not disabled as it is not possible to stake on the same outcome again
- Inputfield is disabled as there is a fixed amount of ETH defined by the reality.eth protocol which need to be staked to change the outcome.

**Figma:**
[Design Specification](https://www.figma.com/file/aTivxuHmp2l6Sn8nho1Ngu/Playground?node-id=455%3A20158)
[Playgrounds](https://www.figma.com/proto/aTivxuHmp2l6Sn8nho1Ngu/Playground?node-id=455%3A20158&viewport=287%2C189%2C0.14576539397239685&scaling=min-zoom)

**Comment by liaojikunwork** [comment]
@pimato , I have a few questions:
-`Finalize Process` is visible if `closing date - 24h` < currentTime < `closing date` ?
- What about `invalid` outcome on your design?

**Comment by pimato** [comment]
> * `Finalize Process` is visible if `closing date - 24h` < currentTime < `closing date` ?

Finalize is currently visible after `closing date` < currentTime 

> What about invalid outcome on your design?

the invalid outcome is now appearing because the market might be invalid. The whole reason why we include the finalizing process is to allow Omen users to participate in the answer finding for which outcome is actually the correct outcome.

**Comment by liaojikunwork** [comment]
@pimato , so should I show Finalize if `currentTime - 24h` < `closing date` < `currentTime` ?
or just show if `closing date` < `currentTime`

**Comment by pimato** [comment]
We already have a logic to show when finalizing, check here: 
https://dxtest.eth.link/#/0x0c8a0b8103e5558240df0dcc626b7261f567034a

you just need to add the reality.eth functionality into it.
