### ISSUE TITLE
Pool Tab is crashing on Rinkeby

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#1266]
<img width="1065" alt="Bildschirmfoto 2020-10-30 um 13 33 28" src="https://user-images.githubusercontent.com/5337809/97705530-8acc1c80-1ab4-11eb-9c69-fdbd6df80bed.png">

**Comment by hexyls** [comment]
This is because we reverted to the original conditional token contract in https://github.com/protofire/omen-exchange/pull/1206

Currently indexed markets use the newer contract.

**Comment by pimato** [comment]
looks like @cag created a pull request for the subgraph to have it synced with the original conditional token contract: https://github.com/protofire/omen-subgraph/pull/76

@KadenZipfel we probably should merge and update the Rinkeby subgraph

**Comment by pimato** [comment]
fixed by merging: https://github.com/protofire/omen-subgraph/pull/76
