### ISSUE TITLE
Changing market currency doesn't change currency being used

### ISSUE THREAD

**Issue by KadenZipfel** [protofire/omen-exchange#1268]
When in a market with multiple currencies, if you are in market buy, sell, or pool view and you change the market currency with this dropdown: 
![image](https://user-images.githubusercontent.com/30579067/97737577-6f541800-1a9a-11eb-9f64-22de915f2706.png)

The currency listed throughout the bottom card doesn't change as well. For example, this market was changed from WETH to DAI, but remains as so:
![image](https://user-images.githubusercontent.com/30579067/97737698-9ad70280-1a9a-11eb-9694-ee9aca01ab67.png)

I haven't checked yet whether the currency being used for transactions changes as well, but it's very important to not forget about this aspect as well.

**Comment by liaojikunwork** [comment]
@KadenZipfel , after changing currency, you should wait a few seconds until the content is updated.

**Comment by KadenZipfel** [comment]
> @KadenZipfel , after changing currency, you should wait a few seconds until the content is updated.

Doesn't resolve at all for me... At least not in the buy/sell/pool views

**Comment by liaojikunwork** [comment]
Ah, make sense what you mean.
