### ISSUE TITLE
Back button behaves unexpectedly after switching currencies in a market

### ISSUE THREAD

**Issue by KadenZipfel** [protofire/omen-exchange#1273]
When switching between currencies, e.g. in this market: https://dxtest.eth.link/#/0x95b2271039b020aba31b933039e042b60b063800, it pushes to the history causing the back button to result in switching to the previous currency instead of the expected effect of going to the homepage.

Is it possible to look through the history and go back to when it was last not on a market page, i.e. when the URL wasn't /#/0x...? If so this would be the optimal solution considering we want to retain whatever filters the user may have had on the last page.

**Comment by liaojikunwork** [comment]
@KadenZipfel , when switching to another currency, what about using `history.replace` instead of `history.push`?
I think `Back button` will work as expected then.

**Comment by KadenZipfel** [comment]
> @KadenZipfel , when switching to another currency, what about using `history.replace` instead of `history.push`?
> I think `Back button` will work as expected then.

Do you mean to simply replace the history with `/`? Because if so, the problem with that is we don't retain any filters the user had when they visited the market

**Comment by liaojikunwork** [comment]
@KadenZipfel , on market details page, when users change currency, we're using `history.push` now.
If we change `history.push` to `history.replace`, it would work.

I just tried, and it worked well.
