### ISSUE TITLE
Verified market displaying as not verified when imported

### ISSUE THREAD

**Issue by KadenZipfel** [protofire/omen-exchange#1279]
![image](https://user-images.githubusercontent.com/30579067/97791597-6134f300-1b91-11eb-9fb6-1fc99f21d068.png)

**Comment by pimato** [comment]
hm.. I can`t replicate this.

**Comment by Mi-Lan** [comment]
@KadenZipfel hey it seems that this issue is fixed by some other pr so i'm closing it
