### ISSUE TITLE
Token balance indicator number not formatted

### ISSUE THREAD

**Issue by KadenZipfel** [protofire/omen-exchange#1281]
![image](https://user-images.githubusercontent.com/30579067/97792626-baa31f00-1b9d-11eb-980d-25a46a03029e.png)

Instead of displaying '86516.63', it should be displaying '86,516.63'

**Comment by Mi-Lan** [comment]
Should i do formatting here also?
![Screenshot 2020-11-02 at 11 25 30](https://user-images.githubusercontent.com/33226956/97857604-4af87580-1cfe-11eb-8396-c903a33f93df.png)
@KadenZipfel
