### ISSUE TITLE
Pool token data section cramped on mobile

### ISSUE THREAD

**Issue by KadenZipfel** [protofire/omen-exchange#1320]
Maybe only one column on small screens? @pimato what do you think?

![D51A91C3-B70C-461C-BCEC-E4E606BB6551](https://user-images.githubusercontent.com/30579067/98454969-97d5b500-211f-11eb-9dca-1ee3a3b7b2fe.png)

**Comment by pimato** [comment]
It should look like this:
<img width="463" alt="pool-mobile" src="https://user-images.githubusercontent.com/5337809/98527043-cc11b880-227a-11eb-8f60-9817f419fa13.png">

**Figma**:
[Design Specification](https://www.figma.com/file/R056tSYMjvfwaFidEBItYy/Widgets-V2?node-id=1209%3A141)
