### ISSUE TITLE
Issues with 3box comments

### ISSUE THREAD

**Issue by KadenZipfel** [protofire/omen-exchange#1321]
- Infinite loading spinner
- Photos not displaying
- Names/addresses not displaying

Not sure if there's actually anything we can do to fix on our side, but worth looking into

![image](https://user-images.githubusercontent.com/30579067/98455014-24807300-2120-11eb-8b39-d6367cd31a2b.png)
![image](https://user-images.githubusercontent.com/30579067/98455020-2f3b0800-2120-11eb-8625-69d117fb70eb.png)

**Comment by hexyls** [comment]
It looks like 3box-comments-react has been [deprecated](https://www.npmjs.com/package/3box-comments-react), they recommend migrating to Ceramic but it is unclear whether they have chat threading support yet. Worth investigating for a better chat experience.
