### ISSUE TITLE
Change no 'my markets' message

### ISSUE THREAD

**Issue by KadenZipfel** [protofire/omen-exchange#1327]
Currently if a user doesn't have any markets and visits the 'My Markets' tab, it will display a message saying, "You have not created any markets yet", instead it should say something more like, "You have not participated in any markets yet."

**Comment by pimato** [comment]
> Currently if a user doesn't have any markets and visits the 'My Markets' tab, it will display a message saying, "You have not created any markets yet", instead it should say something more like, "You have not participated in any markets yet."

Yeah so I would combine both into `You have not created or participated in any markets yet.`
