### ISSUE TITLE
Consolidate spinners

### ISSUE THREAD

**Issue by KadenZipfel** [protofire/omen-exchange#1339]
Currently, on the `verification` branch we have two spinners, `spinnerMain` and `spinnerMainBig`. Instead, we should consolidate these into one and add a size prop so we can set the size based on where it's used. 

**Note**: This should be built on top of, and merged into, the `verification` branch. Same with all other issues labeled `verification`.

**Comment by pimato** [comment]
This should work:
[Loading.svg.zip](https://github.com/protofire/omen-exchange/files/5582609/Loading.svg.zip)
