### ISSUE TITLE
Consider subgraph timeout syncing in useKlerosCuration

### ISSUE THREAD

**Issue by KadenZipfel** [protofire/omen-exchange#1342]
Currently, a 5 second `setTimeout` is used to wait for the subgraph data to sync in `useKlerosCuration`. This may not be the best way to wait for the subgraph to sync (but it may also be the only option). Let's see if there's a better alternative, and if not consider the effects of using this, e.g. is 5 seconds long enough for the subgraph to consistently sync? What happens if it doesn't sync in time? etc..

Please share any thoughts in the comments.

**Note**: This should be built on top of, and merged into, the verification branch. Same with all other issues labeled verification.

**Comment by hexyls** [comment]
resolved in https://github.com/protofire/omen-exchange/pull/1406
