### ISSUE TITLE
Reused component styles should be moved to common_styles file

### ISSUE THREAD

**Issue by KadenZipfel** [protofire/omen-exchange#1344]
Currently, we reuse a bunch of the component styles in the `market_verify` component. Instead, as with all reused component styles, they should exist in the `common_styles` file.

**Note**: This should be built on top of, and merged into, the verification branch. Same with all other issues labeled verification.

**Comment by Mi-Lan** [comment]
@KadenZipfel  i was looking at kleros_curation i found that we reused same piece of code just with textual change for DescriptionText and it's children maybe that can be made into one component within kleros curation? Right button wrapper and all it's children are used 3 times same way also... What do you think?

**Comment by KadenZipfel** [comment]
> @KadenZipfel i was looking at kleros_curation i found that we reused same piece of code 4 times just with textual change for DescriptionText and it's children maybe that can be made into one mini component within kleros curation? Right button wrapper and all it's children are used 3 times same way also... What do you think? My concern is that when we start changing css down the line some mistakes are ripe to crop up with that many duplicates...

Sounds good, can you make an issue for it?

**Comment by Mi-Lan** [comment]
> > @KadenZipfel i was looking at kleros_curation i found that we reused same piece of code 4 times just with textual change for DescriptionText and it's children maybe that can be made into one mini component within kleros curation? Right button wrapper and all it's children are used 3 times same way also... What do you think? My concern is that when we start changing css down the line some mistakes are ripe to crop up with that many duplicates...
> 
> Sounds good, can you make an issue for it?

yeah i will!
