### ISSUE TITLE
Add xDai Button and Bridge/Dropdown

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#1358]
This Bridge allows Omen users to deposit/convert Dai from Ethereum mainnet to the xDai chain. This is enabled by https://bridge.xdaichain.com/ , the official xDai bridge which allows anyone to convert DAI to xDAI.

### xDai Bridge - Mainnet Button
<img width="1408" alt="Header-main" src="https://user-images.githubusercontent.com/5337809/99274925-2c7c9900-282b-11eb-821e-8f76f945c200.png">

### xDai Bridge - xDai Chain Button
<img width="1408" alt="Header-xDai" src="https://user-images.githubusercontent.com/5337809/99277411-12908580-282e-11eb-8648-ca2748fd432f.png">

### Dropdowns

<img width="1132" alt="Dropdowns-xDai" src="https://user-images.githubusercontent.com/5337809/99277581-410e6080-282e-11eb-8068-f5c9092e70e7.png">

**Figma**:
[Playground](https://www.figma.com/proto/aTivxuHmp2l6Sn8nho1Ngu/Playground?node-id=298%3A13737&viewport=534%2C401%2C0.08635475486516953&scaling=min-zoom)
[Design Specification](https://www.figma.com/file/aTivxuHmp2l6Sn8nho1Ngu/Playground?node-id=298%3A13737)

**Comment by liaojikunwork** [comment]
@pimato ,
Arrow Icon between "Dai" and "xDai" is used to switch "Dai -> xDai" and "xDai->Dai" ?
