### ISSUE TITLE
Use transaction modal for showing user the state of the transaction similar to creating a market

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#1371]
currently, if the user requests verification via Kleros, only a metamask modal is popping up.

We should use a modal to show the state of the transaction like we do on buy/sell, deposit/withdraw and create market:
<img width="311" alt="Bildschirmfoto 2020-11-17 um 14 31 03" src="https://user-images.githubusercontent.com/5337809/99396358-ee8e7c00-28e1-11eb-9dc8-87543f229a32.png">

Steps:
- User clicks on Kleros circle icon to enable Kleros verification
- User clicks on Request Verification
- Request Verification button is getting disabled
- Modal is appearing with "Requesting Kleros verification" 
- Once the transaction gets confirmed && the subgraph has the new data the modal should disappear and the verification has started

**Comment by Mi-Lan** [comment]
Request verification contract call will be moved to cpk so that we have easier access to state of transaction and to keep consistency.
