### ISSUE TITLE
Collect 0.05 ETH should not be a hyperlink and has the wrong color

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#1378]
Currently:
<img width="1028" alt="Bildschirmfoto 2020-11-18 um 14 30 10" src="https://user-images.githubusercontent.com/5337809/99536426-a38c6b80-29aa-11eb-96ab-d017a2fd4dfc.png">

Should:
<img width="952" alt="Bildschirmfoto 2020-11-18 um 14 32 01" src="https://user-images.githubusercontent.com/5337809/99536560-d59dcd80-29aa-11eb-92c4-c275aec287d8.png">

**Figma**:
[Design Specification](https://www.figma.com/file/R056tSYMjvfwaFidEBItYy/Widgets-V2?node-id=1209%3A141)

**Comment by Mi-Lan** [comment]
![Screenshot 2020-11-20 at 18 08 02](https://user-images.githubusercontent.com/33226956/99828522-569bc700-2b5b-11eb-9c3b-4500f46b11ac.png)
@pimato should it be changed in this text also?

**Comment by pimato** [comment]
> ![Screenshot 2020-11-20 at 18 08 02](https://user-images.githubusercontent.com/33226956/99828522-569bc700-2b5b-11eb-9c3b-4500f46b11ac.png)
> @pimato should it be changed in this text also?

No, because it is not a bounty but actually a security deposit.
