### ISSUE TITLE
Ends in few seconds should be changed

### ISSUE THREAD

**Issue by Mi-Lan** [protofire/omen-exchange#1387]
Currently once market is requested for verification towards then end it says ends in few seconds for much longer time then few seconds
![Screenshot 2020-11-20 at 21 42 45](https://user-images.githubusercontent.com/33226956/99848041-5ca0a080-2b79-11eb-9328-50eba3d360f4.png)

**Comment by KadenZipfel** [comment]
I'm even getting this error when `timeRemaining === 0` in the 'Challenge period pending' state.
