### ISSUE TITLE
Create Sokol version of Omen

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#1408]
Now that the contracts are installed and running, we need to start getting an omen interface version deployed which is connected to the Sokol network.

**Conditional token contract:**
`0x0Db8C35045a830DC7F2A4dd87ef90e7A9Cd0534f`
https://blockscout.com/poa/sokol/address/0x0Db8C35045a830DC7F2A4dd87ef90e7A9Cd0534f/contracts

**FPMMDeterministicFactory:**
`0x2fb8cc057946DCFA32D8eA8115A1Dd630f6efea5`
https://blockscout.com/poa/sokol/address/0x2fb8cc057946DCFA32D8eA8115A1Dd630f6efea5/contracts

**Kleros bridge:**
`0xFE083F7B16B26582D74Deb57Cf63d755b597eA05`
https://blockscout.com/poa/sokol/address/0xFE083F7B16B26582D74Deb57Cf63d755b597eA05/contracts

Reality.eth contract:
`0x63975d9e7CF434dCd04bD808d8c79d03EF69100B`
https://blockscout.com/poa/sokol/address/0x63975d9e7CF434dCd04bD808d8c79d03EF69100B/transactions

CPK Factory:
`0xaaF0CCef0C0C355Ee764B3d36bcCF257C527269B`
https://blockscout.com/poa/sokol/address/0xaaF0CCef0C0C355Ee764B3d36bcCF257C527269B/contracts

Sokol faucet:
https://faucet.poa.network/

**Comment by hexyls** [comment]
GnosisSafe contract (master copy):
`0x035000FC773f4a0e39FcdeD08A46aBBDBF196fd3`
https://blockscout.com/poa/sokol/address/0x035000FC773f4a0e39FcdeD08A46aBBDBF196fd3/contracts

MultiSend contract:
`0x602DF5F404f86469459D5e604CDa43A2cdFb7580`
https://blockscout.com/poa/sokol/address/0x602DF5F404f86469459D5e604CDa43A2cdFb7580/contracts

DefaultCallbackHandler contract:
`0x1e9C3EBAd833b26E522D2fDa180Af3D2A32459D2`
https://blockscout.com/poa/sokol/address/0x1e9C3EBAd833b26E522D2fDa180Af3D2A32459D2/contracts

Oracle contract:
`0xF6176D7126d7C68a7753F566362C72Ad36AF1e04`
https://blockscout.com/poa/sokol/address/0xF6176D7126d7C68a7753F566362C72Ad36AF1e04/contracts
