### ISSUE TITLE
Deploy Omen with xDai contracts

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#1409]
Once we tested the sokol Omen version with the Kleros bridge, we can start deploying the xDai version for Omen.

**Conditional token contract:**
`0xCeAfDD6bc0bEF976fdCd1112955828E00543c0Ce`
https://blockscout.com/poa/xdai/address/0xCeAfDD6bc0bEF976fdCd1112955828E00543c0Ce/contracts

**FPMMDeterministicFactory:**
`0x9083A2B699c0a4AD06F63580BDE2635d26a3eeF0`
https://blockscout.com/poa/xdai/address/0x9083A2B699c0a4AD06F63580BDE2635d26a3eeF0/transactions

**Kleros bridge:**
`0xa0Baf56D83be19Eb6bA8aFAD2Db812Bc13D8Be1d`
https://blockscout.com/poa/sokol/address/0xa0Baf56D83be19Eb6bA8aFAD2Db812Bc13D8Be1d/contracts

Reality.eth contract:
`0x90a617ed516ab7fAaBA56CcEDA0C5D952f294d03`
https://blockscout.com/poa/xdai/address/0x90a617ed516ab7fAaBA56CcEDA0C5D952f294d03/read-contract

Reality.eth Oracle Adapter
`0x2bf1BFb0eB6276a4F4B60044068Cb8CdEB89f79B`
https://blockscout.com/poa/xdai/address/0x2bf1BFb0eB6276a4F4B60044068Cb8CdEB89f79B/contracts

Reality.eth Scalar Adapter
`0xb97FCb6adf4c4aF9981932a004e6CC47173d0Bfc`
https://blockscout.com/poa/xdai/address/0xb97FCb6adf4c4aF9981932a004e6CC47173d0Bfc/contracts

CPK Factory:
`0xfC7577774887aAE7bAcdf0Fc8ce041DA0b3200f7`
https://blockscout.com/poa/xdai/address/0xfC7577774887aAE7bAcdf0Fc8ce041DA0b3200f7/transactions

**Comment by hexyls** [comment]
GnosisSafe contract (master copy):
`0x6851D6fDFAfD08c0295C392436245E5bc78B0185`
https://blockscout.com/poa/xdai/address/0x6851D6fDFAfD08c0295C392436245E5bc78B0185/contracts

MultiSend contract:
`0x035000FC773f4a0e39FcdeD08A46aBBDBF196fd3`
https://blockscout.com/poa/xdai/address/0x035000FC773f4a0e39FcdeD08A46aBBDBF196fd3/contracts

DefaultCallbackHandler contract:
`0x602DF5F404f86469459D5e604CDa43A2cdFb7580`
https://blockscout.com/poa/xdai/address/0x1e9C3EBAd833b26E522D2fDa180Af3D2A32459D2/contracts

Wrapped xDai contract:
`0xe91D153E0b41518A2Ce8Dd3D7944Fa863463a97d`
https://blockscout.com/poa/xdai/address/0xe91D153E0b41518A2Ce8Dd3D7944Fa863463a97d/contracts

**Comment by pimato** [comment]
Sokol 

Reality.eth Scalar Adapter
`0x86459E9eA6cF4caEe9F8F4cb1203d38EaB3cbD34`
https://blockscout.com/poa/sokol/address/0x86459E9eA6cF4caEe9F8F4cb1203d38EaB3cbD34/transactions
