### ISSUE TITLE
Enable interaction with Omen through the Wallet Connect Safe App

### ISSUE THREAD

**Issue by hexyls** [protofire/omen-exchange#1412]
- Depends on https://github.com/protofire/omen-exchange/pull/1347 so we can identity when the wallet connect provider is the Gnosis Safe interface

- Requires the developers of the Wallet Connect Safe App to enable support for `SEND_TRANSACTIONS_V2` that allows us to set `safeTxGas` (this is out of our control)

- Once both of these are resolved, we need to make sure transaction structure / experience across both the native Omen Safe App and connection through the Wallet Connect Safe App are identical

**Comment by KadenZipfel** [comment]
Do you know if there are any ongoing plans for Wallet Connect Safe App to enable support? If not we should make an issue to signal our interest

**Comment by hexyls** [comment]
Created an issue: https://github.com/gnosis/safe-react-apps/issues/83

Keep in mind that this also depends on the safe apps sdk cutting a new release.
