### ISSUE TITLE
Modify 'Payout' terminology/usage

### ISSUE THREAD

**Issue by KadenZipfel** [protofire/omen-exchange#1420]
This PR https://github.com/protofire/omen-exchange/pull/1417 sparked me to consider more the names we're using to reference values, and whether they're as clear as they can be.

Currently, in the scalar market buy view, when you enter an amount, you get details as to payout and profit/loss. Currently, under payout we are actually displaying the amount of profit, which is inconsistent with plans for the details view https://github.com/protofire/omen-exchange/issues/1393. Instead, I think we should just display the sell value of the users position as is done in the details view.

@pimato what do you think?

**Comment by pimato** [comment]
Yeah this make sense!
I would propose to change the `market buy view` to make it consistent:

- Change `Your Payout` to the total value the user would get back if sold, like we have it in the `market details view`
- Replace the percentage indicator in the `Profit/Loss` with the actually value, like we have on the `market details view`.

It should look similar to this:
<img width="602" alt="Bildschirmfoto 2020-12-09 um 07 42 01" src="https://user-images.githubusercontent.com/5337809/101594724-743dad00-39f2-11eb-9806-33a8401d7345.png">
