### ISSUE TITLE
After selling all my shares, sell button still active on the market overview widget

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#1485]
The UI allows me to go to the Sell UI even if I don`t have any shares to sell:
<img width="616" alt="Bildschirmfoto 2021-01-04 um 15 44 39" src="https://user-images.githubusercontent.com/5337809/103546797-d976a800-4ea3-11eb-9bcc-c2029c14fc38.png">
<img width="615" alt="Bildschirmfoto 2021-01-04 um 15 44 34" src="https://user-images.githubusercontent.com/5337809/103546800-daa7d500-4ea3-11eb-911c-3e76e9cf5fe0.png">

Once the user does not have any shares anymore, the Sell button should be disabled!

**Comment by KadenZipfel** [comment]
Fixed in: https://github.com/protofire/omen-exchange/pull/1482
