### ISSUE TITLE
After resolving market, UI is not showing the winning component

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#1486]
<img width="606" alt="Bildschirmfoto 2021-01-04 um 16 10 20" src="https://user-images.githubusercontent.com/5337809/103549464-b64df780-4ea7-11eb-8bc1-c7065385575d.png">

after a page refresh:
<img width="606" alt="Bildschirmfoto 2021-01-04 um 16 10 35" src="https://user-images.githubusercontent.com/5337809/103549488-bfd75f80-4ea7-11eb-981f-907476e84c87.png">

Also, we should add a divider between the winning component and the buttons

**Comment by KadenZipfel** [comment]
Fixed in: https://github.com/protofire/omen-exchange/pull/1482
