### ISSUE TITLE
Market Configuration process allows to proceed with -500 as a starting point

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#1487]
@KadenZipfel 

a general question, there is no way to have a scalar market with -100 to 200 as the boundaries right?
If no then we should not allow the user to set the starting point with a negative number:
<img width="621" alt="Bildschirmfoto 2021-01-04 um 16 32 00" src="https://user-images.githubusercontent.com/5337809/103551455-a552b580-4eaa-11eb-8e62-377a5e545a0a.png">

**Comment by KadenZipfel** [comment]
Yeah, this should cause problems at the smart contract level. Good find!

**Comment by KadenZipfel** [comment]
Fixed in: https://github.com/protofire/omen-exchange/pull/1482
