### ISSUE TITLE
After reality.eth set the correct outcome, omen is not updating the UI

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#1490]
After reality.eth protocol finalized the answer, the omen UI has not updated and is still showing a pending resolution process:
<img width="617" alt="Bildschirmfoto 2021-01-04 um 17 08 41" src="https://user-images.githubusercontent.com/5337809/103554867-e0a3b300-4eaf-11eb-9e2d-7651241e9935.png">

**Comment by KadenZipfel** [comment]
This would require setting the reality.eth answer directly from Omen like we do with categorical questions now. Otherwise we can't get notified when a new answer has been set because it's at a different website. Once we have a UI to set the answer on Omen, this will be a must though!

**Comment by pimato** [comment]
@Mi-Lan PR: https://github.com/protofire/omen-exchange/pull/1740 will fix this.

**Comment by pimato** [comment]
So I did another test and it seems like the values are not getting updated after the transaction got confirmed:
![Bildschirmaufnahme 2021-04-09 um 10 30 33](https://user-images.githubusercontent.com/5337809/114152995-29d82880-991f-11eb-814e-731af7568ca6.gif)

Only a refresh fixed it after waiting a while:
![Bildschirmaufnahme 2021-04-09 um 10 31 46](https://user-images.githubusercontent.com/5337809/114153374-89cecf00-991f-11eb-9dd4-3ea8b697ef1d.gif)
