### ISSUE TITLE
Creating a scalar market on xDai/Sokol does not work

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#1503]
Just tested the latest commit of the scalar-markets branch and it looks like creating a market on xDai does not work: 

<img width="2163" alt="Bildschirmfoto 2021-01-06 um 14 03 09" src="https://user-images.githubusercontent.com/5337809/103771828-c5a87e80-5028-11eb-826d-cc5ec6c767ca.png">

steps to reproduce:
1) Go to dxtest.eth.link which is the latest commit `256a7cc60fe0162d7ac8e8d02bc6663f17cb2381`
2) Click create market
3) configure a market:
<img width="605" alt="Bildschirmfoto 2021-01-06 um 14 11 58" src="https://user-images.githubusercontent.com/5337809/103772132-47001100-5029-11eb-8e63-11970f4691da.png">
4)Fund market with 5 xDai:
<img width="624" alt="Bildschirmfoto 2021-01-06 um 14 12 07" src="https://user-images.githubusercontent.com/5337809/103772152-51baa600-5029-11eb-94a5-026aa12c6786.png">
5) Metamask pops up
6) Sign transaction
7) Transaction got confirmed:
https://blockscout.com/poa/xdai/tx/0x8b0f11140d79d1a21b1727bf9874287517e1766f1e41098e7231501e35279c2d/token-transfers

But I am not getting redirect to the market details view and:
<img width="653" alt="Bildschirmfoto 2021-01-06 um 14 14 40" src="https://user-images.githubusercontent.com/5337809/103772267-875f8f00-5029-11eb-9e11-98b9a4dde4ff.png">

**Comment by KadenZipfel** [comment]
Fixed in: https://github.com/protofire/omen-exchange/pull/1482
