### ISSUE TITLE
Add option to sell or remove liquidity as native asset

### ISSUE THREAD

**Issue by KadenZipfel** [protofire/omen-exchange#1507]
Currently, it's possible to buy and add funding to a market in the native asset, but not so when it comes to selling or withdrawing.

**Comment by hexyls** [comment]
This might be related to https://github.com/protofire/omen-exchange/issues/1439

Do we want to abstract away wrapped assets in general? Users fund with ETH and withdraw to ETH and wrapping is just handled in the background?

The only downside is losing convenience if a user already has a wrapped asset in their wallet.

Or do we want to keep both?

@Mi-Lan @pRoy24 thoughts?

**Comment by pimato** [comment]
https://github.com/protofire/omen-exchange/pull/1783 will fix this
