### ISSUE TITLE
Include pool data in scalar markets

### ISSUE THREAD

**Issue by KadenZipfel** [protofire/omen-exchange#1512]
Categorical markets have a component which lists various values related to liquidity pooling, e.g. your liquidity, total liquidity, etc.. This should also be included in scalar markets.

**Comment by KadenZipfel** [comment]
@pimato should we reuse the same pool data view used for categorical markets?

**Comment by pimato** [comment]
> @pimato should we reuse the same pool data view used for categorical markets?

Yeah I agree.

I´ve also added infos regarding user receiving additional shares:
<img width="1796" alt="Fund-scalar" src="https://user-images.githubusercontent.com/5337809/106470210-85f67a80-64a0-11eb-940f-81927de391c0.png">

Figma:
[Design Specification](https://www.figma.com/file/aTivxuHmp2l6Sn8nho1Ngu/Playground?node-id=1588%3A47556)
[Playground](https://www.figma.com/proto/aTivxuHmp2l6Sn8nho1Ngu/Playground?node-id=1588%3A47556&viewport=206%2C260%2C0.5617057681083679&scaling=min-zoom)

**Comment by KadenZipfel** [comment]
I've completed the pool data section (in pr above) and exported the additional shares section into this issue: https://github.com/protofire/omen-exchange/issues/1601 so I can refactor the value boxes as well.
