### ISSUE TITLE
[Gelato] Buttons are not: vertically aligned and correct size

### ISSUE THREAD

**Issue by Mi-Lan** [protofire/omen-exchange#1518]
- Buttons in gelato pr are size 40px and in figma 32px
![Screenshot 2021-01-08 at 15 38 25](https://user-images.githubusercontent.com/33226956/104027346-8ebc9f00-51c7-11eb-9737-e446bcefc251.png)
- Gelato icon is size 40px and in figma 38px
- These buttons are not vertically aligned
![Screenshot 2021-01-08 at 15 40 44](https://user-images.githubusercontent.com/33226956/104027579-e0fdc000-51c7-11eb-8596-bb17470d40f1.png)

**Comment by hilmarx** [comment]
Will include in #1481
