### ISSUE TITLE
[Gelato] Bolded text: incorrect color and font-weight

### ISSUE THREAD

**Issue by Mi-Lan** [protofire/omen-exchange#1519]
Places to be corrected:
- For the Gelato part we shouldn't be using p tag and color should be "37474F" instead of #7D8189
![Screenshot 2021-01-08 at 15 45 12](https://user-images.githubusercontent.com/33226956/104028031-8022b780-51c8-11eb-9ed8-50ea9a6c6af3.png)
- In the text below Gelato "Automatically withdraw liquidity 3 days before market ends" the --3 days-- part should be bolded according to the figma
- This part should be font-weight: 500; and color: #37474F; for the bolded text instead of strong tag
![Screenshot 2021-01-08 at 15 47 40](https://user-images.githubusercontent.com/33226956/104028294-d859b980-51c8-11eb-9013-0ffbaac7d7ad.png)
- This part is not bolded according to design as well
![Screenshot 2021-01-08 at 15 51 57](https://user-images.githubusercontent.com/33226956/104028797-72216680-51c9-11eb-8a29-d307e4dd555c.png)
- Instead of using generic green color in scheduled and succesful modals we should be using this green #4B9E98 with font-weight 500 both for text and icons 
![Screenshot 2021-01-08 at 16 05 25](https://user-images.githubusercontent.com/33226956/104030216-54550100-51cb-11eb-978a-d283c89884db.png)
- Failed part should be font-weight 500 as well
![Uploading Screenshot 2021-01-08 at 16.08.47.png…]()
- Withdraw condition and Withdraw Date and Time should be color 37474F, 100%
![Screenshot 2021-01-08 at 16 47 19](https://user-images.githubusercontent.com/33226956/104034452-2d013280-51d1-11eb-8511-1d99341cbd14.png)

**Comment by hilmarx** [comment]
Will include that in #1481

**Comment by Mi-Lan** [comment]
> Will include that in #1481

@hilmarx Hey! I spoke with geronimo and we figured it may be better to create separate branch for the issue and when the issue is done we can then merge it to the #1481 ? What do you think? Because there is enough stuff on that main branch already...

**Comment by hilmarx** [comment]
Hi @Mi-Lan, just discussed with @superarius, he is already working on it, but will put the changes related to #1519 and #1518 onto a separate branch, so we will keep #1481 as it is as you suggested

#1481 is ready for final review btw.

**Comment by Mi-Lan** [comment]
> Hi @Mi-Lan, just discussed with @superarius, he is already working on it, but will put the changes related to #1519 and #1518 onto a separate branch, so we will keep #1481 as it is as you suggested
> 
> #1481 is ready for final review btw.

@hilmarx Hey men i left a review on the gelato branch... Sorry for keeping you guys busy so much. But i think it's in both of dxDao and gelatos interest for this feature to be as good as we can make it!
