### ISSUE TITLE
Remove arbitrary 15 refetches of market maker data

### ISSUE THREAD

**Issue by hexyls** [protofire/omen-exchange#1527]
Market maker data is being refetched [at least 15 times](https://github.com/protofire/omen-exchange/blob/master/app/src/hooks/useGraphMarketMakerData.tsx#L266). If anything awaits this function is takes ages to resolve making the user wait longer than they need to.

**Comment by KadenZipfel** [comment]
I know that the intended effect is to refetch a _maximum_ of 15 times, and using the `needRefetch` check to see if a refetch is necessary. The reasoning for setting it up this way is to wait for the subgraph to update, and to stop refetching once it is updated. I think the caveat though is that if there is no subgraph update it goes through 15 fetches, so there's probably a way to make this more efficient without sacrificing the ability to wait for the subgraph to update as it's a pretty messy solution anyways.
