### ISSUE TITLE
Even if user has min required amount to enable Gelato, Warning still shown

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#1530]
<img width="613" alt="Bildschirmfoto 2021-01-11 um 16 01 26" src="https://user-images.githubusercontent.com/5337809/104198254-4cdd6400-5426-11eb-83fa-955c84b5ec6f.png">

**Comment by superarius** [comment]
This could be a bad UX, happy to adjust somehow, but you have to put more than the amount into the deposit amount input field for the warning to disappear.

**Comment by pimato** [comment]
Totally agree, gonna close this up!
