### ISSUE TITLE
Sokol markets creation/listing no longer working on Sokol testnet

### ISSUE THREAD

**Issue by pRoy24** [protofire/omen-exchange#1554]
After creating a Sokol market and confirming the transaction, I get this error page.
![image](https://user-images.githubusercontent.com/4677914/105022705-a6740d00-5a7c-11eb-8705-a57e849fa3c2.png)

Also none of the markets created on Sokol are visible on the main page.

**Comment by KadenZipfel** [comment]
This _should_ be fixed once we have updated xDai/Sokol arbitration contracts.

**Comment by pRoy24** [comment]
In that case should I close this issue now or wait until the arbitration contracts are updated to verify and then close the issue?

**Comment by KadenZipfel** [comment]
> In that case should I close this issue now or wait until the arbitration contracts are updated to verify and then close the issue?

I think we should keep it open until we verify that it's solved

**Comment by pimato** [comment]
Just created a market on sokol without any issues. Closing for now!
