### ISSUE TITLE
xDai bridge history section and claim option

### ISSUE THREAD

**Issue by Mi-Lan** [protofire/omen-exchange#1559]
- This issue is related to #1358 since we would like users to be able to exchange xDai for Dai without leaving Omen we would need to accompany that with history section with option to claim their DAI
- Here are some suggestions:
Have user history section somewhere within interface so that they can see all their transactions and be able to claim them like on [xDai bridge](https://bridge.xdaichain.com/history)
![Screenshot 2021-01-20 at 00 52 24](https://user-images.githubusercontent.com/33226956/105108091-cc6bd280-5ab9-11eb-82a4-8974d41edbec.png)

**Comment by Mi-Lan** [comment]
@pimato What do you think?

**Comment by KadenZipfel** [comment]
Why do we need to include the history? Is it not possible to do xDai => Mainnet => claim?

**Comment by Mi-Lan** [comment]
> Why do we need to include the history? Is it not possible to do xDai => Mainnet => claim?

@KadenZipfel Well what if someone has multiple claims like i do? Yeah we can exclude the transferred transactions but still something similar has to be done...

**Comment by pimato** [comment]
@Mi-Lan multiple claims should be possible through the gnosis safe proxy kit :)

**Comment by pimato** [comment]
I don`t think we need the history for now, just the ability to claim after the user switched to the other network :)

**Comment by Mi-Lan** [comment]
@pimato Okay so ability to claim most recent transaction with simple button after making transaction on xDai? That will be below the transfer button? Would that work?

**Comment by pimato** [comment]
> @pimato Okay so ability to claim most recent transaction with simple button after making transaction on xDai? Should that be below the transfer button?

I think a simple button which appears on the left of the  ( Dai -> xDai )  button with ` claim 153.21 DAI` is enough for now. Will create a simple design asap.

**Comment by pimato** [comment]
I think a quick fix will be to let a claim button show with the balance:
<img width="1622" alt="Bildschirmfoto 2021-01-21 um 19 20 00" src="https://user-images.githubusercontent.com/5337809/105394329-bb3bd680-5c1d-11eb-82af-45f81f55373b.png">

Design specification:
[Figma](https://www.figma.com/file/R056tSYMjvfwaFidEBItYy/Widgets-V2?node-id=1209%3A141)

**Comment by pimato** [comment]
https://github.com/protofire/omen-exchange/pull/1770 will fix this
