### ISSUE TITLE
Update Kovan/Sokol contracts for Kleros

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#1572]
Contract Name: `RealitioHomeArbitrationProxy`
Network: `Sokol`
Address: `0xd50DdFdDbC069C1D1f7CDA1D8aa4AD8cFb1E9e0F`
Link: https://blockscout.com/poa/sokol/address/0xd50DdFdDbC069C1D1f7CDA1D8aa4AD8cFb1E9e0F/contracts

Contract Name: `RealitioForeignArbitrationProxy `
Network: `Kovan`
Address: `0x22d7134BFF92F36a8609d0C2279c7A7C5B266908`
Link: https://kovan.etherscan.io/address/0x22d7134BFF92F36a8609d0C2279c7A7C5B266908#code

**Comment by KadenZipfel** [comment]
Was there a Rinkeby contract deployed?
