### ISSUE TITLE
Ending soon should be ASC sorted based on closing time

### ISSUE THREAD

**Issue by 0xVenky** [protofire/omen-exchange#1605]
Newest is DESC sorted which is fine, but Ending soon should be ASC sorted so that we always display the ones that are ending soon at the top.

![paste (2)](https://user-images.githubusercontent.com/55109759/106665117-38643580-65a6-11eb-80c7-2f88eb12081a.png)

**Comment by hexyls** [comment]
hmmm I was unable to reproduce this, on master it appears to sort correctly (see screen below). Can anyone else reproduce this?

<img width="561" alt="Screen Shot 2021-02-03 at 2 38 31 pm" src="https://user-images.githubusercontent.com/72715177/106694845-81130180-662d-11eb-8ff2-772701b739f2.png">

**Comment by KadenZipfel** [comment]
I'm guessing this happened on the 'My Markets' view? This is a quick fix we made because previously it was showing first markets that were already closed, which wasn't what we wanted. Ideally it would be in ASC but only displaying markets that have not already closed.
