### ISSUE TITLE
Gnosis Safe interface using safeGas 500000 but xDai gas limit is 496496 need to change the hard coded values

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#1615]
<img width="516" alt="Bildschirmfoto 2021-02-03 um 22 34 56" src="https://user-images.githubusercontent.com/5337809/106812564-2ea70480-6670-11eb-9ba3-e11e173c7971.png">

we are just trying to withdraw liquidity from a market and looks like the transactions are failing:
https://blockscout.com/poa/xdai/tx/0xede75a3e6df6c6e9fc39fb8ecacabb3f2902fee19b9942a46bb145ae38052c6a

we also tried with 495000 safeGas, but it looks like its still uses very low gasEstimations:
https://blockscout.com/poa/xdai/tx/0x9a87826b8c49ad8d83b83f24a9c85f6476c3746c0b2aec1822e88d65c6ee8af8/internal-transactions

**Comment by hexyls** [comment]
resolved in https://github.com/protofire/omen-exchange/pull/1629
