### ISSUE TITLE
New Your-Connection Modal Design Specification

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#1668]
**Connection Modal:**
![your-connection](https://user-images.githubusercontent.com/5337809/109040834-a5af4600-76ce-11eb-8935-0d275e2b1657.png)

Note:
- Deposit is the equivalent to xDai bridge transfer from Ethereum to xDai Network
- Withdraw is the equivalent to xDai bridge transfer from xDai to Ethereum Mainnet
- Omen Account Balance should be from Gnosis Safe on xDai 
- New Deposit/Withdraw process defined in https://github.com/protofire/omen-exchange/issues/1680

Figma:
[Connection Modal - Design Specification](https://www.figma.com/file/aTivxuHmp2l6Sn8nho1Ngu/Playground?node-id=1866%3A41)
[Connection Modal - Playground](https://www.figma.com/proto/aTivxuHmp2l6Sn8nho1Ngu/Playground?node-id=1866%3A41&viewport=108%2C251%2C0.06591392308473587&scaling=min-zoom)

**Comment by KadenZipfel** [comment]
Looks like the image shown is different from the design spec and playground. I'm assuming the design spec is the correct one?

**Comment by KadenZipfel** [comment]
Also, I noticed that having the modal appear on clicking on the address button conflicts with with the dropdown currently used, particularly with the 'claim dai' item.

![image](https://user-images.githubusercontent.com/30579067/109237215-fafa5e80-7785-11eb-9b55-5eb492b8083e.png)

**Comment by pimato** [comment]
> Looks like the image shown is different from the design spec and playground. I'm assuming the design spec is the correct one?

Should be fixed now!
