### ISSUE TITLE
Scalar market page crashes if all liquidity is pulled out and no further action is possible subsequently

### ISSUE THREAD

**Issue by pRoy24** [protofire/omen-exchange#1687]
Steps to reproduce-
Create a scalar market with some initial liquidity.
Go to pool page and withdraw all of the liquidity.
The market page will crash on that and subsequent page loads and you will not be able to do any further actions on that market.

Error
×
TypeError: Reduce of empty array with no initial value

Log

> 223 | const totalDepositedTokens = totalUserShareAmounts.reduce((min: BigNumber, amount: BigNumber) =>
      | ^  224 |   amount.lt(min) ? amount : min,
  225 | )
  226 | 
  
  04 |   setMarketMakerData(newMarketMakerData)
      | ^  205 |   setStatus(Status.Ready)
      
 On refreshing the page the outcome table shows undefined/undefined

If you go to pool page, the view will crash again.

**Comment by KadenZipfel** [comment]
Can confirm, just reproduced

**Comment by pimato** [comment]
great catch! Just replicated!
