### ISSUE TITLE
History table is showing cpk(gnosis safe) address instead of users address

### ISSUE THREAD

**Issue by Mi-Lan** [protofire/omen-exchange#1688]
- Currently we are not getting users address but proxy address because of the JazzIcons which uses address to display unique image it can be clearly seen...
![Screenshot 2021-03-01 at 19 57 05](https://user-images.githubusercontent.com/33226956/109544923-6ca91400-7ac8-11eb-9da3-92c92e858b89.png)

**Comment by Mi-Lan** [comment]
Came to an interesting conclusion....Was researching fpmm smart contracts and i think if in event msg.sender was changed to tx.origin we would have this issue solved...Although i don't know how upgradable or changable these smart contracts are? I would to to play around with it if possible?
![Screenshot 2021-03-18 at 23 05 10](https://user-images.githubusercontent.com/33226956/111703909-9ee3a100-883e-11eb-9619-22b8dae76128.png)

**Comment by hexyls** [comment]
If you want to do this in the frontend for any arbitrary proxy/cpk address, you can use the upcoming [safe service](https://github.com/protofire/omen-exchange/pull/1666/files#diff-6b9fe8d9cd6b32343ed87177b4c8ded9cb9f0027523df52aaf95892a6cb75667R13) which is part of the relay PR. 

You can call safe.getOwners which will return an array of owners and you can use the 0 index owner as the display address.
