### ISSUE TITLE
Fix Meta Tags

### ISSUE THREAD

**Issue by jpkcambridge** [protofire/omen-exchange#1707]
This looks unprofessional to anyone coming across Omen in a google search result:

<img width="512" alt="Screen Shot 2021-03-05 at 9 24 00 PM" src="https://user-images.githubusercontent.com/874683/110193369-240b9680-7df9-11eb-8919-d0ab0b8599ac.png">

Not quite sure what the issue is because there does appear to be a description meta tag in the html; this might require some digging . . maybe removing the noscript tag that does appear in the results?  Here is an article with some detail on meta tags: https://clutch.co/seo-firms/resources/meta-tags-that-improve-seo

**Comment by hexyls** [comment]
Had a look around and seems like a lot of people have issues with google indexing meta tags that are generated with React Helmet (which we use). We should probably hard code meta tags in [index.html](https://github.com/protofire/omen-exchange/blob/master/app/public/index.html)
