### ISSUE TITLE
Finalized market showing wrong message

### ISSUE THREAD

**Issue by Mi-Lan** [protofire/omen-exchange#1728]
- Market in question http://localhost:3001/#/0xcc20b65ea47549fe246663da2cf8942273443e23
- Seems that this RINKEBY market is showing congratulations message and resolve condition at the same time
![Screenshot 2021-03-11 at 12 52 52](https://user-images.githubusercontent.com/33226956/110783840-39ede100-8269-11eb-9c81-6690965c7fca.png)
- When i click resolve i'm getting error 

>  There was an error resolving the condition with question id '0x11304d29d7754081bdd9dcaed5951d110059d771591bcb66121784f5d5e5e12e' execution reverted: condition not prepared or found

![Screenshot 2021-03-11 at 12 57 54](https://user-images.githubusercontent.com/33226956/110783984-686bbc00-8269-11eb-8243-69cb32f37f04.png)

**Comment by Mi-Lan** [comment]
@KadenZipfel could this just be that its old ?

**Comment by KadenZipfel** [comment]
I figured it out, looks like you're right @Mi-Lan, the market was created before the realitio proxy contract was deployed, so it must only exist on the previous realitio proxy causing resolution to fail.
