### ISSUE TITLE
incorrect earnedCollateral amount when redeeming

### ISSUE THREAD

**Issue by hexyls** [protofire/omen-exchange#1739]
`earnedCollateral` can be too high when [transferring from the cpk to the user](https://github.com/protofire/omen-exchange/blob/master/app/src/services/cpk.ts#L1142), causing transactions to fail. 

example [tx](https://dashboard.tenderly.co/tx/xdai/0x8a6ed0d6877a774012de6a135ea196f1a171c7072ee2c47a424010235d3e40b3) where the amount redeemed from the conditional tokens contract is 4327888365033786**67371** but we try to transfer 4327888365033786**87044** from the cpk to the user.

**Comment by pimato** [comment]
https://github.com/protofire/omen-exchange/pull/1786 potentially fixed this, closing for now.
