### ISSUE TITLE
Increase the required deposit amount

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#1747]
Currently the Omen UI is showing:
<img width="405" alt="Bildschirmfoto 2021-03-18 um 18 14 43" src="https://user-images.githubusercontent.com/5337809/111668416-03d6d100-8816-11eb-9c1a-224819df93ed.png">

we should rename it to 
```You need to deposit at least 5 DAI.```

**Comment by gem1no** [comment]
Hi, sorry where is this located in the UI? I see where the logic is in codebase...

`const minDeposit = exchangeType === ExchangeType.deposit ? parseEther('0.005') : parseEther('10')`

But not able to see this modal anywhere on app. Is this outdated bc of the new transaction modal PR?
