### ISSUE TITLE
Max sell failing on xDai

### ISSUE THREAD

**Issue by KadenZipfel** [protofire/omen-exchange#1757]
It looks like there is a rounding issue when selling on xDai, whether through the relayer or not. Selling a little less than the max amount works. Same issue on scalar and categorical markets.

Possibly related to: https://github.com/protofire/omen-exchange/issues/1739 but I haven't been able to reproduce a failing redeem.

**Comment by hexyls** [comment]
related: https://github.com/protofire/omen-exchange/issues/1676
