### ISSUE TITLE
When trying to buy Outcome tokens on xDai chain transaction fails 

### ISSUE THREAD

**Issue by Mi-Lan** [protofire/omen-exchange#1764]
Steps to repoduce:

1. Connect to xDai on metamask
2. Go into any market
3. Try to buy outcome tokens

> I didn't do this on my main account that has xDai tokens enabled so i think this is issue with new account that don't have xDai enabled and prompt didn't show as you can see in video below

https://user-images.githubusercontent.com/33226956/111993713-3be05b80-8b17-11eb-807d-0818584020e7.mov

**Comment by pimato** [comment]
Can reproduce:

1. Transfer xDai to new Ethereum Account
2. Switch to new Ethereum Account
3. Go to market: http://localhost:3000/#/0x09ba10798a54f8830e3568a000e55981c493f043
4. click buy & try to purchase outcome tokens
5. BUG: Error Modal appears:
<img width="659" alt="Bildschirmfoto 2021-03-22 um 15 09 00" src="https://user-images.githubusercontent.com/5337809/112002797-8fa37280-8b20-11eb-88b1-12f7c0220dac.png">
<img width="609" alt="Bildschirmfoto 2021-03-22 um 15 08 45" src="https://user-images.githubusercontent.com/5337809/112002799-90d49f80-8b20-11eb-8ea7-3fc29a16c6ea.png">

**Comment by KadenZipfel** [comment]
https://github.com/protofire/omen-exchange/blob/78769390f0c2249ff3a6d865cd38578cc0b4e078/app/src/services/cpk.ts#L1227
Looks like we're skipping the proxy update check on xDai for some reason, which is preventing the necessary proxy upgrade set allowance component from displaying. I also noticed that if you visit from a different address on a new network, the set allowance component appears, but clicking 'Set' does nothing.
