### ISSUE TITLE
Make it obvious that user has claimable DAI

### ISSUE THREAD

**Issue by KadenZipfel** [protofire/omen-exchange#1787]
When you withdraw DAI via the relayer, it's not obvious that you still need to claim it, and you can only see that once you navigate to the 'Your connection' modal. It would be nice if there was some kind of notification letting the user know to open the modal and claim their DAI

**Comment by pimato** [comment]
I think one way of doing it is by adding a second action into the withdrawal process modal:

So once a user actually went through the whole withdrawal process on xDai, we show him this:
![claim](https://user-images.githubusercontent.com/5337809/113145490-c3704d80-922e-11eb-90a6-13259cb19cd4.png)

steps: 
![chaim-modals](https://user-images.githubusercontent.com/5337809/113145564-daaf3b00-922e-11eb-9b8f-a6bf606fd5b1.png)

**Figma**:
[Design Specification](https://www.figma.com/file/R056tSYMjvfwaFidEBItYy/Widgets-V2?node-id=3832%3A241)
