### ISSUE TITLE
After user redeemed winning, congratulation message still showing

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#1788]
Network: Mainnet/xDai Relayer

After redeeming my winning shares the UI is still showing the congratulion box even I already redeemed my winnings:
<img width="607" alt="Bildschirmfoto 2021-03-29 um 11 46 52" src="https://user-images.githubusercontent.com/5337809/112819059-78b2d200-9084-11eb-8eed-2f3a11a77800.png">

After refresh:
<img width="616" alt="Bildschirmfoto 2021-03-29 um 11 47 31" src="https://user-images.githubusercontent.com/5337809/112819153-8ff1bf80-9084-11eb-9e91-88287ee7d989.png">

**Comment by Mi-Lan** [comment]
I couldn't replicate it https://www.dropbox.com/s/mp5a3ufmaf1ltmc/Screen%20Recording%202021-03-30%20at%2013.34.40.mov?dl=0 heres video
