### ISSUE TITLE
'Your liquidity' should reference total value of liquidity instead of just withdrawal value

### ISSUE THREAD

**Issue by KadenZipfel** [protofire/omen-exchange#1845]
Currently 'Your liquidity' references the withdrawal value of your liquidity, but ignores the additional shares you'd receive if you were to withdraw at a non 50/50 probability. Instead, similarly to total pool liquidity it should actually display the full value of your liquidity. One way of doing this might be to calculate the percentage of total pool tokens owned by the user and multiply that by `marketMakerData.scaledLiquidityParameter`. Alternatively, it may be better to create a subgraph property which is somehow related to the account entity.

**Comment by pimato** [comment]
closed for now.
