### ISSUE TITLE
Continue with xDai button should not redirect user to home page

### ISSUE THREAD

**Issue by KadenZipfel** [protofire/omen-exchange#1878]
If you visit an xDai market while connected to xDai on the base URL (omen.eth.link), you will get the below modal prompting you to continue with xDai which when clicked will redirect you to the home page. Instead it should keep you on the same page but simply update the URL to xdai.omen.eth.link/#/0x....

![image](https://user-images.githubusercontent.com/30579067/116722745-a6e14580-a993-11eb-930e-0fca044da671.png)

Additionally, we should be able to detect that it's an xDai market and not show this modal at all.

**Comment by hexyls** [comment]
closed by https://github.com/protofire/omen-exchange/pull/1890
