### ISSUE TITLE
Add guild proposal creation to batch actions on market creation

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#1913]
Requires https://github.com/protofire/omen-exchange/issues/1912 to be done & merged. Once the user deploys a liquidity rewards contract, we should add the creation of a guild proposal with the request of funding a fixed amount of OMN tokens.

- Create Proposal via [ERC20 Guild function ](https://github.com/AugustoL/dxdao-contracts/blob/main/contracts/erc20guild/ERC20Guild.sol#L243)
- Proposal duration: 3 days
- No Quorum
- `> 50% Vote Wins`

**Comment by KadenZipfel** [comment]
Closing as this will now be done at the smart contract level
