### ISSUE TITLE
xDai tight integration users can't redeem reality staked funds

### ISSUE THREAD

**Issue by KadenZipfel** [protofire/omen-exchange#1948]
A user in discord set a reality outcome using their Omen account and now can't access the bonded amount. I'm guessing the issue is that the UI is simply not checking if their relay address can collect the bond

Debug market link for reference: https://omen.eth.link/#/0x443a7c4bd462d202699516de0b3b25892a346e26?debugAddress=0x36bed53B24f982ea2f4b231b3763Cf453401E50D

**Comment by pimato** [comment]
I think to move quick here we should merge the  redeem winnings with redeem bonds and change the messaging slightly from:
```You have bought 2.95 Shares of the winning outcome which can be redeemed for 2.95 DAI.```

to:
```You can now redeem 2.95 DAI from your 2.95 Shares of the winning outcome and 0.1 ETH from bonding on the finalized outcome.```

If the user did not bond any ETH we should show:

```You can now redeem 2.95 DAI from your 2.95 Shares of the winning outcome.```
