### ISSUE TITLE
[REFACTOR] Handling all text styling across codebase

### ISSUE THREAD

**Issue by Mi-Lan** [protofire/omen-exchange#1997]
Current situation:
- When we have some text field we usually just create new styled component, add appropriate colors from theme, certain font-weight and font-size....
- This sometimes creates a lot of unnecessary styled components which just clutter up top portion of component

Solution:
- In my two weeks i worked with swapr I really liked this pattern and it made development so much easier and code much more readable. So uniswap has about 13 variations of text which in most cases have just 2 or 3 properties defined(font-size, font-weight and is some cases color but it can be ovewritten) and rest of text variations can be added with inline styles.... 
- how it looks like :
![Screenshot 2021-06-16 at 12 43 08](https://user-images.githubusercontent.com/33226956/122205326-69cc0680-cea0-11eb-8bcd-21290074e9f7.png)

Example of it in code:
![Screenshot 2021-06-16 at 12 45 49](https://user-images.githubusercontent.com/33226956/122205647-c92a1680-cea0-11eb-81df-5829627f5950.png)

This would require good alignment with figma so we keep it consistent. This could make development process much faster! If we have types for every text field and reinforce it with code reviews. What do you guys think @KadenZipfel @hexyls @pimato

**Comment by KadenZipfel** [comment]
This is a good call, and I think the most important part is that we have a consistent strategy. Currently, we're doing this for some components and not for others. For example, `button_styling_types` is a well defined set of buttons that are easily reusable and we should use this as a reference for other similar reusable components.

**Comment by Mi-Lan** [comment]
> This is a good call, and I think the most important part is that we have a consistent strategy. Currently, we're doing this for some components and not for others. For example, `button_styling_types` is a well defined set of buttons that are easily reusable and we should use this as a reference for other similar reusable components.

Couldn't agree more ! Part of this refactor can be just using reusing stuff that already in there and cleaning it up a bit so its simpler to reuse. But in my opinion we need to rework that buttons folder wayy to many options that I think none of us know how to use properly...

**Comment by KadenZipfel** [comment]
> > This is a good call, and I think the most important part is that we have a consistent strategy. Currently, we're doing this for some components and not for others. For example, `button_styling_types` is a well defined set of buttons that are easily reusable and we should use this as a reference for other similar reusable components.
> 
> Couldn't agree more ! Part of this refactor can be just using reusing stuff that already in there and cleaning it up a bit so its simpler to reuse. But in my opinion we need to rework that buttons folder wayy to many options that I think none of us know how to use properly...

If, like you said, we get consistency in naming between figma and the codebase then it will make it real easy to know which components to use.
