### ISSUE TITLE
[REFACTOR] Separation of concerns with Component structure

### ISSUE THREAD

**Issue by Mi-Lan** [protofire/omen-exchange#2002]
- So this is very common react pattern that we kind of use in our codebase but not to its full potentional
- Its means that basically there is clear decoupling of logic(js,calcualtion,sorting) that component needs.... from view(style,html,css) here is a great article going more in depth regarding this (https://www.g2i.co/blog/react-separation-of-concerns)
- So we kind of use this I saw throughout the code that we use containers and components inside them which should encapsulate this issue,  so that logic is inside the container and when logic is sorted in Container it is passed to view component which sole purpose it to display it and not do any logic/js work
- But in most cases we are just making component with view and logic together which can be hard to read and maintain and creates overbloated components
- Taking uniswap again as example most of their components inside components folder are just view components and inside the pages folder they are handling handling logic along with combining all the components from components folder together
@KadenZipfel @pimato @hexyls what do you guys think?

**Comment by Mi-Lan** [comment]
@KadenZipfel As we discussed in friday meeting this change would be very time consuming and would require significant effort to accomplish. But I still believe if we incorporate this into our codebase it would really clear things up a lot and push us into top notch front-end codebases out there since only handful of codebase have nailed this down. So my suggestion is to do it as we go along. For example if we are doing some change on component that hasn't got this pattern ingrained that we should reinforce it with code reviews and slowly start building. 

Vague suggestion on what to keep in mind:
1)First tip would be to decouple VIEW components into reusable parts as much as we can and to keep them in components folder
2)To fill that empty pages folder with combined components from components folder and to try to keep LOGIC in pages folder as much as we can

**Comment by KadenZipfel** [comment]
> @KadenZipfel As we discussed in friday meeting this change would be very time consuming and would require significant effort to accomplish. But I still believe if we incorporate this into our codebase it would really clear things up a lot and push us into top notch front-end codebases out there since only handful of codebase have nailed this down. So my suggestion is to do it as we go along. For example if we are doing some change on component that hasn't got this pattern ingrained that we should reinforce it with code reviews and slowly start building.
> 
> Vague suggestion on what to keep in mind:
> 1)First tip would be to decouple VIEW components into reusable parts as much as we can and to keep them in components folder
> 2)To fill that empty pages folder with combined components from components folder and to try to keep LOGIC inside pages folder and components as much as we can

I definitely think this is worth doing. It also coincides with some existing plans to dry up the code, e.g. giving scalar and categorical components a shared logic container component.
