### ISSUE TITLE
Omen market creation failed on xDai

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#2006]
A user reached out to me regarding a market not showing up on Omen on xDai:
https://xdai.omen.eth.link/#/0xa1701027dbe6a6eff30347b6e801e44a1bd430dc

It looks like the batched cpk transaction failed to create the market, more infos can be found here:
https://blockscout.com/poa/xdai/tx/0x216646914736ae3cb948704448e439e85907eeff584c4739282725016964958b

might this be related to: 
https://github.com/protofire/omen-exchange/pull/1959 @hexyls ?

**Comment by hexyls** [comment]
Yep exactly right @pimato tx mentioned above is an out of gas error resolved by https://github.com/protofire/omen-exchange/pull/1959
