### ISSUE TITLE
Style guides

### ISSUE THREAD

**Issue by KadenZipfel** [protofire/omen-exchange#2009]
Below style guides should be included in a `developer.md` file if/when agreed upon (discussion below!). These notes are pretty opinionated, other opinions are super welcome. 

Everyone should take some time to lightly read through the docs mentioned. I don't think we need to be super strict with this, but should aim to be pretty consistent. No shame in missing things here since it's pretty informationally dense, but we should all be pointing out where each other misses things.

- **Git style guide**
    - https://udacity.github.io/git-styleguide/
    - Focus on type and subject
    - Body & footer can be generally ignored
- **Typescript style guide**
    - https://google.github.io/styleguide/tsguide.html
    - Seems to be already in use in the codebase for the most part
- **React style guide**
    - https://github.com/airbnb/javascript/tree/master/react
        - Linter seems to follow a lot of these rules automatically
    - Logic should be separated from views
        - See: https://www.g2i.co/blog/react-separation-of-concerns
- **Issue style guide**
    - Some of this will be done/modified by @pimato. Main focus should be on title, description and label.
    - Title 
        - Should clearly and briefly describe the issue. Should use an imperative tone, e.g. use 'change' instead of 'changed' or 'changes'.
    - Description 
        - Should clearly explain **what** needs to be done and **why** it needs to be done. May also briefly explain **how** it can be done.
    - Assignment
        - All issues should have someone assigned at some point.
    - Label
        - Should set priority
        - Should categorize task, e.g. `bug`, `enhancement`, or a milestone.
    - Milestone
        - If relevant, the issue should be included in an open milestone.
- **Pull request style guide**
    - [Link PR to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue)
    - Title
        - Clearly explains **what** was done and **why**.
    - Description
        - Briefly explains the changes made.
        - Test cases if relevant.
    - Reviewer
        - Should request suggested reviewer (if active contributor).
            - This is who is most likely to be familiar with the code modified.
- **Review guide**
    - Checklist: https://www.evoketechnologies.com/blog/code-review-checklist-perform-effective-code-reviews/
    - In general I think we should aim to have one code reviewer + @pimato if there is a change to the views.
        - Reviewer should leave with a high degree of confidence in the quality of the code.
    - Often we should invite multiple contributors to test the changes without reviewing the code (at least not in too much detail).

**Comment by Mi-Lan** [comment]
This is great! I would add one suggestion don't know if this is scope of style guide but maybe in the future we could also incorporate something like I mentioned here https://github.com/protofire/omen-exchange/issues/2002#issuecomment-864911078 into requirements....?

**Comment by KadenZipfel** [comment]
> This is great! I would add one suggestion don't know if this is scope of style guide but maybe in the future we could also incorporate something like I mentioned here [#2002 (comment)](https://github.com/protofire/omen-exchange/issues/2002#issuecomment-864911078) into requirements....?

Good call! Added

**Comment by Mi-Lan** [comment]
@KadenZipfel Im wondering did you maybe make some custom configuration in your local git to incorporate git commit messages? I know that you can make custom git configuration dunno if we can go that far to get git messages in it?

**Comment by KadenZipfel** [comment]
> @KadenZipfel Im wondering did you maybe make some custom configuration in your local git to incorporate git commit messages? I know that you can make custom git configuration dunno if we can go that far to get git messages in it?

I don't have anything like that set up, but we could set up a pre-commit hook to force us to follow the correct convention
