### ISSUE TITLE
[REFACTOR] Removal of Compound Logic

### ISSUE THREAD

**Issue by Mi-Lan** [protofire/omen-exchange#2012]
- As we discussed on Omen Refactor call on Friday 18.06 we will remove compound logic for now
- It was also outlined in Kadens document https://hackmd.io/Ql5odKsvQCKscLQScG4A6w
- @KadenZipfel @hexyls are we definitely proceeding with this?

**Comment by hexyls** [comment]
@Mi-Lan yes definitely removing 👍
