### ISSUE TITLE
[REFACTOR] Replace functions related to conditional tokens with Polymarket ones

### ISSUE THREAD

**Issue by Mi-Lan** [protofire/omen-exchange#2014]
As @KadenZipfel suggested in refactor meeting as well as in this doc https://hackmd.io/Ql5odKsvQCKscLQScG4A6w
- We should replace our functions related to conditional token framework with poly market ones from here https://github.com/Polymarket/amm-maths

**Comment by KadenZipfel** [comment]
To clarify, may not need to replace existing functions, but would be good to use this as a template to organize/test what we have. So we should have functionally the same thing but maybe with different naming and parameters to avoid changing around existing uses of our functions (although in some cases this is probably good to do).
