### ISSUE TITLE
[REFACTOR] Improve ending soon filter

### ISSUE THREAD

**Issue by Mi-Lan** [protofire/omen-exchange#2017]
- Currently ending soon filter sometimes causes issues. In particular when its combined with My Markets since it doesn't show markets then when we switch to newest it shows newly created markets.
- We should improve it or replace it 
@KadenZipfel anything we should add?

**Comment by KadenZipfel** [comment]
IMO we should keep it around but include a new default My Markets filter. Something that might be good could be to sort by position size. Will need a subgraph update though, so curious if anyone has other ideas as I see this as an area that we could really improve upon.

**Comment by pimato** [comment]
Filter by:
- position size
- Ending Soon
- liquidity provision size
- redeemable markets

**Comment by pimato** [comment]
Todo:
- try to add position size filtering as default
- Keep existing filters.
