### ISSUE TITLE
Eliminate race conditions in useEffects 

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#2030]
On state management: We likely have a lot of hidden race conditions in useEffects across the app - would be great to come up with a reusable, clean solution/wrapper we can use to prevent them: https://maxrozen.com/race-conditions-fetching-data-react-with-useeffect

**Comment by hexyls** [comment]
The changes made to connection handling recently will have solved a lot of the race conditions I was talking about, safe to close this now and resolve other race conditions normally as they pop up.
