### ISSUE TITLE
[REFACTOR] Better folder structure inside Components folder (1 day)

### ISSUE THREAD

**Issue by Mi-Lan** [protofire/omen-exchange#2035]
- Currently we have lot of examples of over-bloated folders which are not organised and hard to read
- Also I think we should maybe think about and plan more how our directory is structured so we have clear picture of where each component should go...
- I would suggest as starting place to look at components/common and components/market folder since most of our unorganized parts of components are centered there, especially the components/market/common which needs to be fixed urgently, it has too many stuff in there 
- @KadenZipfel @hexyls Maybe some more input here?

**Comment by KadenZipfel** [comment]
My general thoughts on what might be good are:
- Grouping (non-common) components by views
  - e.g. non-common components used in market buy view should be grouped in market buy directory
    - Can then additionally be grouped by section if desired/necessary
- Grouping common components by type (can still go inside a common folder)
  - e.g. various card components go together (this is where we should define standards for them)

**Comment by Frankaus** [comment]
Hey @Mi-Lan @KadenZipfel

There are many components obviously used across different market sections so it's impossible to list these shared components in every single market section where they're being used (e.g both in `market_buy` and `market_sell` folder). I'm thinking though it would be efficient to start this issue by making another `common` folder in the `market/sections`. That should alleviate the mess within some folders such as the `components/common` and `components/market/common` as Milan mentioned. Though it would add another 'common' folder to the entire repo.

Let me know what you think pls

**Comment by Frankaus** [comment]
Smthg that also seems missing is an `images` folder where we can group all the svg images we have, 53 files

![Screenshot 2021-07-29 at 18 39 14](https://user-images.githubusercontent.com/57708955/127531165-531565ee-b278-4252-bfc6-d609ad46fa99.png)

**Comment by KadenZipfel** [comment]
> Smthg that also seems missing is an `images` folder where we can group all the svg images we have, 53 files
> 
> ![Screenshot 2021-07-29 at 18 39 14](https://user-images.githubusercontent.com/57708955/127531165-531565ee-b278-4252-bfc6-d609ad46fa99.png)

Ideally we should be using .tsx files for svg's (essentially just an svg wrapped in a react component), which I think we're mostly doing pretty well with, particularly in the icons directory. Looking at your screenshot it seems most of these svg's are in the build folder, those aren't an issue, but imo any that aren't in the build folder should be organized and wrapped in a react component.

**Comment by KadenZipfel** [comment]
> Hey @Mi-Lan @KadenZipfel
> 
> There are many components obviously used across different market sections so it's impossible to list these shared components in every single market section where they're being used (e.g both in `market_buy` and `market_sell` folder). I'm thinking though it would be efficient to start this issue by making another `common` folder in the `market/sections`. That should alleviate the mess within some folders such as the `components/common` and `components/market/common` as Milan mentioned. Though it would add another `common` folder to the entire repo.
> 
> Let me know what you think pls

I think that's a good idea. Generally imo a good way to think about managing shared components is to place them at the lowest point in the directory tree that each parent component shares. Speaking of directory trees, to go with this issue it would be super cool if you could autogenerate a directory diagram similar to the one below, should be some vscode extension that will do this (if not don't spend too much time on it).
