### ISSUE TITLE
currency filter still shows `All` after picking ETH on Rinkeby

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#2054]
https://user-images.githubusercontent.com/5337809/123857440-93fed900-d922-11eb-9d6f-4d7fd67d2388.mov

Steps to reproduce:

1. Go to http://localhost:3000/#/liquidity
2. Filter by Categorical Markets
3. Click on the Filter Button
4. Pick ETH as currency --> BUG: Currency dropdown button is showing ALL now

**Comment by KadenZipfel** [comment]
Sir, https://github.com/protofire/omen-exchange/issues/2051 😆
