### ISSUE TITLE
[STYLE GUIDE] Issue templates

### ISSUE THREAD

**Issue by Mi-Lan** [protofire/omen-exchange#2064]
- Looking at our style guides issue I think we can further improve issues by using templates to support what Kaden mentioned
- Heres article outlining https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository
- Also @AugustoL did it great for dxVote repo it can be be also reused heres link https://github.com/AugustoL/dxvote/issues/new/choose

What this template should include from original style guide Kaden made https://github.com/protofire/omen-exchange/issues/2009

Issue style guide
Some of this will be done/modified by @pimato. Main focus should be on title, description and label.
Title
Should clearly and briefly describe the issue. Should use an imperative tone, e.g. use 'change' instead of 'changed' or 'changes'.
Description
Should clearly explain what needs to be done and why it needs to be done. May also briefly explain how it can be done.
Assignment
All issues should have someone assigned at some point.
Label
Should set priority
Should categorize task, e.g. bug, enhancement, or a milestone.
Milestone
If relevant, the issue should be included in an open milestone.

@KadenZipfel @pimato what do you guys think?

**Comment by KadenZipfel** [comment]
Great idea! Especially useful to get users to leave detailed bug reports and such
