### ISSUE TITLE
Frontend breaks after user tries to change wallet connection

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#2083]
**Describe the bug**
So it looks like after merging https://github.com/protofire/omen-exchange/pull/2061 we introduced a bug which appears once a user wants to change the connection. Here is a showcase about it:
![Bildschirmaufnahme 2021-07-07 um 10 49 16](https://user-images.githubusercontent.com/5337809/124731407-7c22e880-df12-11eb-9c04-18bce845697d.gif)

**To Reproduce**
1. Click on the Connection button at the top right corner
2. Click on the change button
3. The error is not appearing straight away, so waiting a couple of seconds will crash the app.

**Expected behavior**
The app should not crash after the user tries to change the connection.

**Desktop (please complete the following information):**
 - OS: Mac OS bigSur 11.2.1 (20D74)
 - Browser Brave
 - Version 1.26.74 Chromium: 91.0.4472.124 (Offizieller Build) (x86_64)

**Comment by Mi-Lan** [comment]
I took a stab at this issue its something related to connectors I couldn't quite figure it out. I need to dig more since this is uncharted territory for me... never worked with this stuff...
