### ISSUE TITLE
Blockscout link not working for claiming OMN tokens via xDai tight integration

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#2178]
**Describe the bug**
So it seems like the link to blockscout on the transaction modal for claiming OMN tokens via xDai tight integration is broken. It gives you a blockscout link with page not found.

**Expected behavior**
Link should open up a blockscout page from the correct relayed transaction.

**Screenshots**
https://user-images.githubusercontent.com/5337809/129031348-fe125079-6aba-47cc-90ff-ea502c421caf.mov

**Comment by KadenZipfel** [comment]
I've actually reproduced this on a different app and had the same issue. Even the link etherscan was giving me was not working, so I think the issue is simply that blockscout is failing to index transactions

**Comment by pimato** [comment]
> I've actually reproduced this on a different app and had the same issue. Even the link etherscan was giving me was not working, so I think the issue is simply that blockscout is failing to index transactions

Will revisit in the coming days in close if fixed by blockscout.

**Comment by hexyls** [comment]
Yeah just tested out a normal xdai buy and had the same issue, hopefully resolves itself 👍
