### ISSUE TITLE
proxyFactory.getTransactionHash is not a function

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#2218]
**Describe the bug**
It seems like it is not possible to interact with the xDai tight integration anymore. Buying/Selling/Deposit even create market is always throwing:
```proxyFactory.getTransactionHash is not a function```.

**To Reproduce**
1. Go to http://localhost:3000/#/liquidity
2. Connect to Ethereum Mainnet and use the xDai tight integration
3. Go to http://localhost:3000/#/0xd5f4e3344caa6bc9c54b8db347d282940455cb46
4. Click on `Buy`
5. Fill input with test amount 
6. Click on `Buy`
4. See error:
<img width="434" alt="Bildschirmfoto 2021-08-20 um 14 54 36" src="https://user-images.githubusercontent.com/5337809/130236324-2230d651-40c8-4553-b413-d91c28332274.png">

**Expected behavior**
Any action on xDai should open up metamask with the request to sign the transaction.

**Comment by hexyls** [comment]
hmmmm was unable to reproduce, are you still getting this issue?

**Comment by pimato** [comment]
can`t reproduce either anymore. Closing until it gets relevant again!
