### ISSUE TITLE
Remove bottom space in scalar market slider component in order to make it more reusable

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#2231]
**Describe the task that needs to be done**
With the new proposal details view, it seems that the scalar market slider component was not really made to be reused somewhere else mainly because it includes margin-bottom which should be removed.
<img width="610" alt="Bildschirmfoto 2021-08-30 um 13 22 49" src="https://user-images.githubusercontent.com/5337809/131333137-fc3f2bec-0377-4a80-9e70-4bcbb4fbb360.png">

**Comment by Mi-Lan** [comment]
solved in https://github.com/protofire/omen-exchange/pull/2233
