### ISSUE TITLE
Based on what sort criteria are markets shown?

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#731]
Looking at the current list, I cannot figure how this list is sorted:
<img width="603" alt="Screenshot 2020-05-27 at 10 54 22" src="https://user-images.githubusercontent.com/5337809/82998908-98164400-a008-11ea-8c97-883867dab837.png">

Is it sorted at all?

**Comment by KadenZipfel** [comment]
This is fixed with https://github.com/protofire/omen-exchange/pull/860 since it displays the current sorting criteria.

**Comment by leolower** [comment]
Default sort is now "total Volume"
