### ISSUE TITLE
Insufficient Balance should only be visible if the user has balance lower then his input

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#734]
Right now, the user gets immediately confronted with error messages when the user clicks on buy/sell. 

Currently:
<img width="335" alt="Screenshot 2020-05-27 at 11 10 43" src="https://user-images.githubusercontent.com/5337809/83000563-d3b20d80-a00a-11ea-964d-bab1795d03d5.png">

This message should only be visible if the user has balance lower then his input.

**Comment by gabitoesmiapodo** [comment]
@pimato could you check if this problem still persists?

I don't seem to be able to replicate it, so maybe it was already fixed and we forgot to close this issue.

**Comment by gabitoesmiapodo** [comment]
@pimato I got to replicate the issue. It seems it's triggered whenever `balance === 0`, but otherwise it's fine.

Anyways, I'll look into it.
