### ISSUE TITLE
New Category and Market State Picker

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#801]
The current Category picker was designed/defined with the thinking that there will only be a fixed amount of categories on realit.io which turns out is not true. On realit.io you can actually define any type of category which makes it clear that we need to find a better way of letting the user explore categories in an easy and understandable way.

**Previous:**
<img width="834" alt="market overview" src="https://user-images.githubusercontent.com/5337809/84424807-e63e6080-ac20-11ea-991b-9ac5f8d64eb6.png">

**Version 2:**
<img width="834" alt="market overview" src="https://user-images.githubusercontent.com/5337809/84499902-cf951980-acb3-11ea-8158-73ce8d217924.png">

**Deliverables:**
- Remove the horizontal category picker and replace it with the Category dropdown
- Remove the horizontal navigation for market state and replace it with the Market state dropdown

**Figma:**
[Playground](https://www.figma.com/proto/GNoehJ64fqfptghsjYqvTJ/Playground-V2?node-id=2401%3A41199&viewport=650%2C766%2C0.25712457299232483&scaling=min-zoom)
[Design Specification](https://www.figma.com/file/GNoehJ64fqfptghsjYqvTJ/Playground-V2?node-id=2401%3A41199)

Estimated Time:
8h

Total Bounty:
**320$** (8h * 40$ per hour)
**600 REP (0.049%)** DXdao reputation

**ATTENTION: The estimated time and bounty is just my personal estimations and are not a officially ratified by the collective. Feel free propose a different estimate/bounty**

**Comment by nickplace** [comment]
Hello! I can take this and then take a look at issue #804 . The bounty looks fair to me as well!

Nick

**Comment by nickplace** [comment]
Implemented new UI with hard-coded categories & states here - https://github.com/nickplace/gnosis-conditional-exchange/tree/801-new-pickers

**Comment by nickplace** [comment]
So it looks like querying those numbers for open/pending/closed markets isn't going to be simple.

Here's a PR for a category & status picker without the counters.

https://github.com/protofire/gnosis-conditional-exchange/pull/851
