### ISSUE TITLE
Add possibility to create a custom category on market creation

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#804]
with the [new category and market state picker ](https://github.com/protofire/gnosis-conditional-exchange/issues/801) we need to enable the creation of custom categories on the market creation process. Currently only 7 categories are enabled on Omen. We would like to remove a hardcap on categories.

**Current:**
<img width="834" alt="current-category-picker" src="https://user-images.githubusercontent.com/5337809/84508049-06722c00-acc2-11ea-9113-a36de88de3f2.png">

**Version 2:**
<img width="834" alt="new-category-picker" src="https://user-images.githubusercontent.com/5337809/84507958-ec384e00-acc1-11ea-890d-8789b048173b.png">

**Deliverables:**
- Add Inputfield into the the collapsed category picker 
- inputfield placeholder should be `Add Category...`
- Once user defined a new Category the inputfield should go into the select state

**Figma:**
[Design Specification](https://www.figma.com/file/R056tSYMjvfwaFidEBItYy/Widgets-V2?node-id=1%3A953)

**Estimated Time:**
5h

**Total Bounty:**
200$ (5h * 40$ per hour)
300 REP (0.024%) DXdao reputation

**ATTENTION: The estimated time and bounty is just my personal estimations and are not a officially ratified by the collective. Feel free propose a different estimate/bounty**

**Comment by nickplace** [comment]
Hello! I can take this and then take a look at issue #801 . The bounty looks fair to me as well. Cheers!
