### ISSUE TITLE
[Suggestion] Better fee display

### ISSUE THREAD

**Issue by clesaege** [protofire/omen-exchange#807]
We had the feedback that the "fee" was way to high for a new product. By calling it fee, people assume it goes to a company or holders of a security-like token. I suggest calling it "Liquidity Fee" instead.
I also think we should display the base price before the fee, as otherwise the focus in on the fee, not the base price.

![image](https://user-images.githubusercontent.com/8873352/84576379-3990ea00-adac-11ea-89ba-3359bb8f6e2c.png)

![fee](https://user-images.githubusercontent.com/8873352/84576385-457cac00-adac-11ea-9136-7e710b0a5846.png)

![image](https://user-images.githubusercontent.com/8873352/84576452-c89e0200-adac-11ea-8d4d-54dfc95eee66.png)

**Comment by pimato** [comment]
@clesaege I like your feedback regarding switching Base cast with Fee as the Basecost should be the first thing the user should see.

I don`t think there is a lot to gain to introduce a new term which most of the users will not know and especially not care about `Liquidity fee`. Keeping it simple and just call it a `Fee` is in my view the best way.

**Comment by clesaege** [comment]
Uniswap users already know it as "Liquidity Provider Fee"
![image](https://user-images.githubusercontent.com/8873352/84603145-13d71400-ae84-11ea-976e-661e1bd67da5.png)
So suggestion is actually to keep terms people are used to.

In other prediction markets "fees" refers to fees paid to the company or token holders. So by using the term there, it makes Omen look less attractive than it actually is.
Omen has 0% fees and I think it's an important competitive feature that users must know.

Another possibility would be to keep the word "fee" but put a hover on it with a text like "Fee going to liquidity providers".

**Comment by KadenZipfel** [comment]
> Another possibility would be to keep the word "fee" but put a hover on it with a text like "Fee going to liquidity providers".

I think this is the best plan. @pimato wyt?
