### ISSUE TITLE
Markets not loading

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#812]
reproducable:

1. Go to https://conditional.netlify.com/
2. Filter only Kleros Markets
3. Switch back to all Arbitrator.
4. BUG --> market will not load anymore
<img width="618" alt="Screenshot 2020-06-16 at 13 46 14" src="https://user-images.githubusercontent.com/5337809/84770395-c66bbb80-afd7-11ea-97f5-347444d96cb8.png">

**Comment by gabitoesmiapodo** [comment]
Not sure if I'm following, but it seems to be working. Maybe it's a temporary problem?

![Jun-16-2020 10-55-36](https://user-images.githubusercontent.com/4015436/84783845-04f57c00-afc0-11ea-958a-b90c86e3a62c.gif)

**Comment by pimato** [comment]
Hey @gabitoesmiapodo I think it works but just very very slow:
http://cloudflare-ipfs.com/ipfs/QmeFDEBavQ28u1yWgAVbL3YJvH3wGdyUi58ex6QMCU1pAA

**Comment by gabitoesmiapodo** [comment]
@pimato we could close this if you think it's not a problem anymore.

**Comment by pimato** [comment]
@gabitoesmiapodo did you saw my ipfs hosted video? loading all markets takes more then 5 minutes.

**Comment by gabitoesmiapodo** [comment]
Yeah, just re checked this.

It seems Rinkeby works fine, but Mainnet is having trouble (not sure if this is related to the problem).

I followed the steps, and after step 4 I changed currency a few times. It worked fine, so it might be a problem with the Arbitrators select.
