### ISSUE TITLE
Add Market Overview Widget

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#817]
One of the main issues currently with the design is that it doesn`t give the user an overview about which state a market is in. On Omen, there are in total 4 market states:

1 Market Open
2 Market Finalizing
(2.5) Market Arbitration
3 Market Closed

Those states should be visualised via a progressbar:

**Market Open state** 

![New](https://user-images.githubusercontent.com/5337809/84912506-ca700a00-b0b9-11ea-9a7f-5b6c5652cc28.png)

**Market Finalized state** 

![New](https://user-images.githubusercontent.com/5337809/84912745-086d2e00-b0ba-11ea-9f64-46c894c04d4d.png)

**Market Arbitration state**

![New](https://user-images.githubusercontent.com/5337809/84912830-2175df00-b0ba-11ea-8dd7-58e5178fe941.png)

**Market Closed state**

![New](https://user-images.githubusercontent.com/5337809/84912945-4407f800-b0ba-11ea-93bc-5576c615cf1a.png)

If the user wants to see the Trade History Chart, clicking on it will collapse the widget:
![New-Collapsed](https://user-images.githubusercontent.com/5337809/84913880-46b71d00-b0bb-11ea-8f93-41a2e6d692fd.png)

if the user clicks on politics, he will get redirected to the markets overview with the filter enabled for only showing market with category politics.

if the user clicks on realit.io, he will get redirected to the realit.io dapp with the market question

if the user clicks on DXdao, he will get redirected to the markets overview with the filter enabled for only showing market with DXdao as an arbitrator.

**Figma:**
[Design Playground](https://www.figma.com/proto/GNoehJ64fqfptghsjYqvTJ/Playground-V2?node-id=2471%3A29&viewport=167%2C573%2C0.4466730058193207&scaling=min-zoom)
[Design Specification](https://www.figma.com/file/GNoehJ64fqfptghsjYqvTJ/Playground-V2?node-id=2471%3A1)

**Comment by Phinneas** [comment]
So I've been talking with Geronimo and I think I'll take this on as the first thing I do.

**Comment by KadenZipfel** [comment]
@Phinneas Any progress?

**Comment by pimato** [comment]
Hey @Phinneas I am going to reassign it to @KadenZipfel
