### ISSUE TITLE
Show markets user bough/sold outcome shares and created markets in my markets

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#824]
Currently, only markets the user has created are showing up in my markets. We should use the my markets tab to show all actives from the user which includes:

- created markets
- bought shares
- liquidity provided

**Comment by leolower** [comment]
We are discussing this with Alan to see if it can be implemented using thegraph.

**Comment by leolower** [comment]
Depends on https://github.com/protofire/omen-subgraph/issues/14
