### ISSUE TITLE
New token should automatically fetch icon

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#828]
The DXdao just added USDT to its Omen token registry. It seems like the UI doesn´t know where to get the icon for USDT.
How is Omen fetching the Icons?

<img width="812" alt="Screenshot 2020-06-20 at 19 16 15" src="https://user-images.githubusercontent.com/5337809/85207737-32795700-b32b-11ea-9f30-69863f8f296b.png">

**Comment by namesty** [comment]
I'd like to tackle this one with @cbrzn

**Comment by namesty** [comment]
Currently there is a catalog of token icons: https://github.com/protofire/gnosis-conditional-exchange/tree/master/app/src/components/common/icons/currencies. These icons are exported here: https://github.com/protofire/gnosis-conditional-exchange/blob/master/app/src/components/common/icons/currencies/currencies_data.tsx. 

If the icon is found, then it is rendered, if not, it just shows the symbol (https://github.com/protofire/gnosis-conditional-exchange/blob/master/app/src/components/market/common/currency_selector/index.tsx#L71).
