### ISSUE TITLE
Use multiple token registries (DXdao, Kleros) to show verified markets

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#837]
On default, show only markets which have been added to the curated market registry which is currently in the process of being added here:

http://alchemy.daostack.io/dao/0x519b70055af55a007110b4ff99b0ea33071c720a/scheme/0x252d4c96bc18c6e0670f5cebeda40d6997688223d9498c8a61e0cb45c2c0a3ff

users can filter by Market Validity (VALID/INVALID) where default is VALID:
<img width="923" alt="Screenshot 2020-06-23 at 12 57 09" src="https://user-images.githubusercontent.com/5337809/85395842-0dfec400-b551-11ea-9af5-977106f60e2e.png">

if a users clicks on an invalid market a warning should signal that there is a pending verification by the DXdao:
<img width="594" alt="Idle" src="https://user-images.githubusercontent.com/5337809/85395981-43a3ad00-b551-11ea-8a0c-ab29d47e1960.png">

if the market has been added to the list, the market detail view should have no message anymore and we include a verified icon on the question like this:
<img width="880" alt="Screenshot 2020-06-23 at 13 01 16" src="https://user-images.githubusercontent.com/5337809/85396259-b57bf680-b551-11ea-8dc3-557788feabb5.png">

**Deliverables**:

- fetch all valid markets from the OmenCurationlist and load the subgraph data
- add dropdown filter for market validity
- add warning message on market detail view if a market is not on the OmenCurationList

**Figma:**
[Filter Dropdown
](https://www.figma.com/file/8ewqNUtmCOryLQDZiP6Rfc/V1?node-id=121%3A1001)
[Market Detail Message](https://www.figma.com/file/8ewqNUtmCOryLQDZiP6Rfc/V1?node-id=211%3A17297)
Estimated Time:
6h

**Total Bounty:**
240$ (6h * 40$ per hour)
360 REP (0.0296%) DXdao reputation

ATTENTION: The estimated time and bounty is just my personal estimations and are not a officially ratified by the collective. Feel free propose a different estimate/bounty

**Comment by KadenZipfel** [comment]
> I may have mistaken what was supposed to be implemented. I thought the UI should display market validity based on the field `klerosTCRregistered` of the [protofire/omen-subgraph#40](https://github.com/protofire/omen-subgraph/pull/40) so that's what I went ahead to implement.

I'm actually not sure what we have in mind for having two different curation registries. @pimato Do you have anything in mind for this?

**Comment by KadenZipfel** [comment]
Anything left to do for this or is it ready to be closed? I guess we still want to add a warning for unverified markets?

**Comment by mtsalenc** [comment]
Yes, the current warning also includes a button to request verification.

For Kleros curation it should be a redirect to the Omen Verified Markets on Curate with the fields prefilled.

**Comment by pimato** [comment]
gonna create a new issue specifically for the "verify your market process".

**Comment by pimato** [comment]
I´ve created an issues about the verification process: https://github.com/protofire/omen-exchange/issues/1118
