### ISSUE TITLE
Filtering by high liquidity is not working

### ISSUE THREAD

**Issue by mariano-aguero** [protofire/omen-exchange#865]
Filtering by high volume is not working.
[This market](https://dxtest.eth.link/#/0x592af74865799e1ed509afef002a6eca26e1caa2 ) has 50k funding but when I list markets sorted by liquidity it doesnt show up.

The my markets filter also doesn’t work  right now

**Comment by mariano-aguero** [comment]
I was doing some research in the  [omen graph](https://thegraph.com/explorer/subgraph/gnosis/omen), I fetch the list of markets with this query just to check the order and see what is happening
```
{
  fixedProductMarketMakers(orderBy: "liquidityParameter", orderDirection: "desc") {
    id
    liquidityParameter
  }
}
```
Next, I take two markets to compare, one with [DAI](https://dxtest.eth.link/#/0x55f0b47c208296058472ad25462c612d035d465a) and the other with [USDC](https://dxtest.eth.link/#/0x592af74865799e1ed509afef002a6eca26e1caa2) as funding.

Analyzing the result of queries in thegraph, we can see that the order is working fine, but the `liquidityParameter` property is not taking into account the decimals (18 for DAI, 6 for USDC)

USDC Image
![Screenshot_20200701_151939](https://user-images.githubusercontent.com/1144028/86279159-f60dec80-bbaf-11ea-9868-3b89e66c9955.png)

DAI Image
![Screenshot_20200701_152003](https://user-images.githubusercontent.com/1144028/86279162-f73f1980-bbaf-11ea-9ae2-08a1cc54fd01.png)

**Comment by leolower** [comment]
This is probably related to #867

**Comment by mariano-aguero** [comment]
The same problem happens with the `collateralVolume`
![Screenshot_20200701_155657](https://user-images.githubusercontent.com/1144028/86281185-839f0b80-bbb3-11ea-89e3-59607fea1999.png)

**Comment by pimato** [comment]
@mariano-aguero @leolower @cag what are the next steps here?

**Comment by mariano-aguero** [comment]
> @mariano-aguero @leolower @cag what are the next steps here?

Mmm I think the value must be `normalized`, of course taking decimals into account . I wonder if it is possible to do this in the graph

**Comment by cag** [comment]
Yeah, this was an oversight when I was adding scaled versions of the fields. I should have also added this field.
