### ISSUE TITLE
winning message missing padding

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#873]
<img width="642" alt="Screenshot 2020-07-02 at 11 11 48" src="https://user-images.githubusercontent.com/5337809/86340357-0fb53f80-bc55-11ea-8c2a-74f177e706e4.png">

**Comment by KadenZipfel** [comment]
To confirm, is the issue here the lack of margin/padding between the box and the line below it?

**Comment by pimato** [comment]
fixed with: https://github.com/protofire/omen-exchange/pull/912
