### ISSUE TITLE
Dust amount remains after user sold/bought outcome tokens

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#886]
Transaction:
https://etherscan.io/tx/0x5ee238099f984c0349950519b3b4667f83f6af5b1daff44bd247c5f49fb11342

screenshot:
![Screenshot (8)](https://user-images.githubusercontent.com/5337809/86529401-bc3f2d80-beb0-11ea-9624-e7a2b9e3a707.png)

if the user decides to sell all its shares/buy with all assets, there should be no dust!

**Comment by mariano-aguero** [comment]
Working on it ...
