### ISSUE TITLE
Market has invalid Market Category "cryptocurrency"

### ISSUE THREAD

**Issue by nicoelzer** [protofire/omen-exchange#887]
- This market has category "cryptocurrency" instead of "Cryptocurrency" and cannot be found when using the category filter "Cryptocurrency": https://omen.eth.link/#/0x417e2d9b8b4b7017b0bc7924d158a96a164fb4df

**Comment by KadenZipfel** [comment]
Is it necessarily invalid? I believe in Omen V2 we plan on being able to [create custom categories](https://github.com/protofire/omen-exchange/issues/804). 

This being said, I definitely think categories should **not** be case sensitive, and thus "cryptocurrency" and "Cryptocurrency" should not be separate markets.

**Comment by nickplace** [comment]
If you run this branch: https://github.com/nickplace/gnosis-conditional-exchange/tree/801-new-pickers You'll be able to see all the categories that are currently available to choose from. Knocking out #804 today. Will make the transaction with the lowercase name, and then Capitalize in the UI on #801

**Comment by pimato** [comment]
@KadenZipfel would it make sense to automatically change the input to upper case categories?

**Comment by KadenZipfel** [comment]
> @KadenZipfel would it make sense to automatically change the input to upper case categories?

I think it would be best to store the categories as lowercase on the back-end and capitalize them in the UI as Nick seems to have planned.

**Comment by pimato** [comment]
This issue is fixed!
