### ISSUE TITLE
 I cannot redeem my winning bet: "Error trying to redeem."

### ISSUE THREAD

**Issue by legitimatehuman** [protofire/omen-exchange#891]
I placed a bet on the question: Will "TheBlock" publish an article about Omen?

Here is the link to it: https://omen.eth.link/#/0x6e9e4c68be16cf643c5bd5342689cfae22c9210f

My bet was correct and so I attempted to redeem my funds. When I clicked the "Redeem" button, this happened:

![error](https://user-images.githubusercontent.com/67919427/86618266-1f5fbb80-bfa8-11ea-8902-db2eca322376.png)

Prior to clicking the redeem button, I connected to the site via MetaMask. I reproduced this error on both Chromium and Firefox. After clicking "Try Again", nothing happens. No MetaMask pop-up ever occurs. I have closed and reopened my browser many times to no avail. I even tried changing my IP, but that did not work either.

Each time this error occurs, the following will be printed into my browser console:
```
>gnosis-conditional-exchange::Services::CPKService Error trying to resolve condition or redeem for question id '0xd025299965b7dfb0241dafea3cfdebd72986b55995a9e27f19f77adbccf2711e' invalid data for function output (arg="data", errorArg="success", errorValue="0x", value="0x", reason="insufficient data for boolean type", version=4.0.46)

>gnosis-conditional-exchange::Market::ClosedMarketDetail  -  invalid data for function output (arg="data", errorArg="success", errorValue="0x", value="0x", reason="insufficient data for boolean type", version=4.0.46)
```

**Comment by clesaege** [comment]
![image](https://user-images.githubusercontent.com/8873352/86637312-d833f380-bfc4-11ea-849a-759d6f9768e6.png)
Screenshot

**Comment by cmalfesi** [comment]
We are working on it trying to reproduce the problem and detect the cause.

**Comment by jpkcambridge** [comment]
Getting the same error on the same market.

**Comment by clesaege** [comment]
It's not market specific, it also occurs to old markets I've made before the launch.

**Comment by hpmaxi** [comment]
After we get a hotfix of gnosis/contract-proxy-kit#80 we expect to solve this error.

**Comment by pimato** [comment]
@cmalfesi @hpmaxi seems like this issue was not fixed

**Comment by pimato** [comment]
Just tried to redeem:
<img width="541" alt="Screenshot 2020-07-09 at 13 58 39" src="https://user-images.githubusercontent.com/5337809/87037341-56261380-c1ec-11ea-94b4-87c70981c181.png">

<img width="370" alt="Screenshot 2020-07-09 at 13 58 43" src="https://user-images.githubusercontent.com/5337809/87037355-5a523100-c1ec-11ea-8278-17a0cb153d0d.png">

**Comment by cag** [comment]
Okay, after some troubleshooting, I believe this is the real cause: https://github.com/gnosis/contract-proxy-kit/issues/82

Will make sure this gets resolved for real this time.

**Comment by macor161** [comment]
Myself and other people are still experiencing this issue (see comments on https://omen.eth.link/#/0x18636a5b0991ef889e2c117416a789810c18aca2), any ETA on a possible fix?

**Comment by jpkcambridge** [comment]
Hi @macor161 There is an updated version of Omen currently being proposed and voted on which is on track to pass in a little under 17 hours: https://alchemy.daostack.io/dao/0x519b70055af55a007110b4ff99b0ea33071c720a/proposal/0xf4d34dd806b6253366cf89c58b9b41d674f476c2f7c0d5173ed73801eb60fc4f

**Comment by macor161** [comment]
@jpkcambridge Awesome, thanks!
