### ISSUE TITLE
Add additional info about the potential risk of outcome token buyers regarding removal of liquidity

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#915]
<img width="843" alt="Screenshot 2020-07-09 at 19 07 34" src="https://user-images.githubusercontent.com/5337809/87069438-78815680-c217-11ea-9b3e-67a0b594a4dd.png">

**Comment by KadenZipfel** [comment]
Can be closed with https://github.com/protofire/omen-exchange/pull/916?
