### ISSUE TITLE
add more sophisticated routing

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#918]
Currently, everytime the user navigates back to the main market view it will always show the default view omen.eth.link.

I believe this is bad UX as it should navigate back to the state the user configured with. With that we need to introduce a more sophisticated routing:

default market view when visting `omen.eth.link` => `omen.eth.link/#/24h-volume/` (based on the default sort criteria)
if user changed the sort criteria to `Total Volume` => `omen.eth.link/#/volume/`
if user changed the sort criteria to `Newest` => `omen.eth.link/#/newest/`
if user changed the sort criteria to `Ending soon` => `omen.eth.link/#/ending/`

**For filter functions:**
if user filters by Currency like DAI => `omen.eth.link/#/24h-volume/currency/dai`
if user filters by Currency like DAI and by arbitrator => `omen.eth.link/#/24h-volume/currency/dai?arbitrator=kleros`

**Comment by KadenZipfel** [comment]
Currently working on this, and everything is looking good except for the currency route, it will be a lot easier to use the currency address instead of the name. So instead of `omen.eth.link/#/24h-volume/currency/dai` it would be `omen.eth.link/#/24h-volume/currency/0x...`.

If we really want to use the currency name we can but it would require a map of all currencies in each network, so I figured we could just do that later on.

**Comment by KadenZipfel** [comment]
Also, if we use a search query for the arbitrator (`?arbitrator=kleros`), the arbitrator will not be maintained in the route history. Is this the desired effect?

**Comment by pimato** [comment]
> Also, if we use a search query for the arbitrator (`?arbitrator=kleros`), the arbitrator will not be maintained in the route history. Is this the desired effect?

great point! 

we should probably add:
if user filters by arbitrator => `omen.eth.link/#/24h-volume/&arbitrator=kleros`

**Comment by pimato** [comment]
> Currently working on this, and everything is looking good except for the currency route, it will be a lot easier to use the currency address instead of the name. So instead of `omen.eth.link/#/24h-volume/currency/dai` it would be `omen.eth.link/#/24h-volume/currency/0x...`.
> 
> If we really want to use the currency name we can but it would require a map of all currencies in each network, so I figured we could just do that later on.
> 
> Edit: Also we're looking at the same thing for the arbitrator.

totally fine with having the first version that way and we can think about to improve the UX. I am worried that the URL will just get too big!

**Comment by KadenZipfel** [comment]
> if user filters by arbitrator => `omen.eth.link/#/24h-volume/&arbitrator=kleros`

Looks like this has the same effect. I'll go with: `omen.eth.link/#/24h-volume/arbitrator/kleros`

**Comment by pimato** [comment]
Another important route would include:

categories:

All Categories should be default as http://omen.eth.link/#/24h-volume
Cryptocurrencies picked => http://omen.eth.link/#/24h-volume/cryptocurriencies

market state:
the market state `Open` should be default as http://omen.eth.link/#/24h-volume
if a category is picked and market state `Ended` => http://omen.eth.link/#/24h-volume/cryptocurrencies?state=ended

**Comment by KadenZipfel** [comment]
> if a category is picked and market state `Ended` => http://omen.eth.link/#/24h-volume/cryptocurrencies?state=ended

Are we okay with not maintaining the route in history from using the search query? Or should we switch that up to `/state/ended`?
