### ISSUE TITLE
all category and market state leads to an empty markets view without any way back via navigation

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#926]
steps for reproduction:

1. change market state to ended
2. click on the right arrow until you see this:
<img width="604" alt="Screenshot 2020-07-12 at 02 47 13" src="https://user-images.githubusercontent.com/5337809/87236435-04e37300-c3ea-11ea-9727-94883a68c8f3.png">

the arrow-right button should be disabled if it leads you to an empty market list view

**Comment by KadenZipfel** [comment]
This one is weird. I can only manage to consistently reproduce it if I go to the last page of the open markets, then switch to ended markets and go to the next page.

**Comment by pimato** [comment]
> This one is weird. I can only manage to consistently reproduce it if I go to the last page of the open markets, then switch to ended markets and go to the next page.

seems to be fixed now!

**Comment by KadenZipfel** [comment]
I can still reproduce this, but I think I know the solution.
