### ISSUE TITLE
Oracle and Arbitrator should both be shown

### ISSUE THREAD

**Issue by jpkcambridge** [protofire/omen-exchange#933]
Right now the UI show's "Oracle/Arbitrator" and then displays Kleros.  Kleros is the arbitrator, but Realit.io, at least in most cases, is the oracle.

<img width="313" alt="Screen Shot 2020-07-13 at 1 56 23 PM" src="https://user-images.githubusercontent.com/874683/87337646-c8129b80-c511-11ea-9725-a1d4d6ece5b5.png">

**Comment by KadenZipfel** [comment]
Should this display as: Arbitrator/Oracle Kleros/Realitio?

**Comment by pimato** [comment]
I would just remove the Oracle description for now
