### ISSUE TITLE
bug: sorting of "ending soon"

### ISSUE THREAD

**Issue by Jefgeno** [protofire/omen-exchange#952]
the sorting of "ending soon" should sort the list from closest date to longest in future
![15 1](https://user-images.githubusercontent.com/62712672/87680738-12985000-c77e-11ea-8c9a-223c5c6df4a7.jpg)

**Comment by KadenZipfel** [comment]
I can't reproduce this... Could you share steps to reproduce?

**Comment by pimato** [comment]
Yeah I think something is wrong it, steps to reproduce:

1) go to dxtest.eth.link
2) change the sorting to "ending soon" which looks like this:
<img width="617" alt="Screenshot 2020-07-16 at 23 57 14" src="https://user-images.githubusercontent.com/5337809/87726853-2369b580-c7c0-11ea-8cb3-abe53e092fb1.png">

3) click on any market to see the details
4) go back to the markets overview 
--> bug: the list looks like this:
<img width="622" alt="Screenshot 2020-07-16 at 23 57 21" src="https://user-images.githubusercontent.com/5337809/87726874-2b295a00-c7c0-11ea-907c-00dcc39a9a6e.png">
