### ISSUE TITLE
Users can add liquidity on finalized markets

### ISSUE THREAD

**Issue by KadenZipfel** [protofire/omen-exchange#960]
![image](https://user-images.githubusercontent.com/30579067/87730014-884eec80-c77b-11ea-92fd-332255e35a2c.png)

I'm assuming still having the active 'Pool Liquidity' button on finalized markets is so users can withdraw liquidity, but I'm sure we don't want users to be able to add liquidity to a finalized market.

**Comment by pimato** [comment]
yeah let me think about what the best way is!

**Comment by KadenZipfel** [comment]
This will be extra important once we've fixed https://github.com/protofire/omen-exchange/issues/998

**Comment by KadenZipfel** [comment]
I think a good way to do this would be to default to withdraw and disable the deposit button.

**Comment by pimato** [comment]
100% @KadenZipfel !

something like this:
<img width="633" alt="Screenshot 2020-08-04 at 20 00 19" src="https://user-images.githubusercontent.com/5337809/89328102-26541980-d68d-11ea-9a70-32677ee6e27d.png">
