### ISSUE TITLE
If market has liquidity removed, display tooltip on buy and sell buttons

### ISSUE THREAD

**Issue by KadenZipfel** [protofire/omen-exchange#968]
Currently, in the case that all liquidity is removed from a market, the buy and sell buttons are simply disabled, causing some confusion. To remedy this, I think we should have a tooltip that appears on hover of the buy and sell buttons that says something along the lines of: 'Trading has been disabled due to lack of liquidity.'

**Comment by pimato** [comment]
Hey @KadenZipfel the current fix is in my view not optimal as it requires a mouse/pointer which is not available on the mobile experience. An alert message should be sufficient to communicate mobile/desktop users what is going on:

<img width="698" alt="Screenshot 2020-07-31 at 14 15 25" src="https://user-images.githubusercontent.com/5337809/89034074-8585f700-d338-11ea-80b1-0f1c7456aa1a.png">

**Figma**:
[Design Specification](https://www.figma.com/file/R056tSYMjvfwaFidEBItYy/Widgets-V2?node-id=139%3A203)
