### ISSUE TITLE
Replace horizontal asset picker with asset dropdown in fund market widget

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#995]
Omen is using a horizontal asset picker which should be replaced with an asset-picker via dropdown:

<img width="777" alt="Screenshot 2020-07-24 at 18 38 09" src="https://user-images.githubusercontent.com/5337809/88414249-d6e43280-cddc-11ea-982d-a96239880bf8.png">

**Figma:**[
Design Playground](https://www.figma.com/proto/GNoehJ64fqfptghsjYqvTJ/Playground-V2?node-id=3452%3A177&viewport=515%2C755%2C0.5033186078071594&scaling=min-zoom)
[Design Specification
](https://www.figma.com/file/GNoehJ64fqfptghsjYqvTJ/Playground-V2?node-id=3452%3A177)

**Comment by KadenZipfel** [comment]
Is there, and should there be, any way to enter max. balance?

**Comment by pimato** [comment]
> Is there, and should there be, any way to enter max. balance?

Yes, 100%!
